Imports System.Data
Imports System.Data.OleDb
Imports inoGenDLL

Public Class konfession
    Private connectionString As String = String.Format("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=""{0}"";", My.Settings.DBPath)

    Private dt As New DataTable()

    Private isNewRecord As Boolean = False
    Private ID As Integer? = Nothing

    Public Sub New()
        InitializeComponent()

        LoadData()
    End Sub

    Private Sub dgKonfession_MouseDoubleClick(sender As Object, e As MouseButtonEventArgs)
        Dim rowView As DataRowView = CType(dgKonfession.SelectedItem, DataRowView)
        If rowView IsNot Nothing Then
            ID = Convert.ToInt32(rowView("tblKonfessionID"))
            txtKonferssionKurz.Text = rowView("Konfessionkurz").ToString()
            txtKonferssion.Text = rowView("Konfession").ToString()
            isNewRecord = False
        End If
    End Sub

    Private Sub btnSave_Click(sender As Object, e As RoutedEventArgs) Handles btnSave.Click
        Dim rowView As DataRowView = CType(dgKonfession.SelectedItem, DataRowView)
        If rowView IsNot Nothing Then
            ' Werte in DataRow ändern
            rowView("Konfessionkurz") = txtKonferssionKurz.Text
            rowView("Konfession") = txtKonferssion.Text

            ' Änderungen in Access speichern
            Try
                Using conn As New OleDbConnection(connectionString)
                    conn.Open()
                    If isNewRecord Then
                        Dim insertCmd As New OleDbCommand("INSERT INTO tblKonfession (Konfession, Konfessionkurz) VALUES (?, ?)", conn)
                        insertCmd.Parameters.AddWithValue("@Konfession", txtKonferssion.Text)
                        insertCmd.Parameters.AddWithValue("@Konfessionkurz", txtKonferssionKurz.Text)
                        insertCmd.ExecuteNonQuery()
                        MessageBox.Show("Neuer Datensatz gespeichert!")
                    ElseIf ID.HasValue Then
                        ' VORHANDENEN Datensatz updaten
                        Dim updateCmd As New OleDbCommand("UPDATE tblKonfession SET Konfession = ?, Konfessionkurz = ? WHERE tblKonfessionID = ?", conn)
                        updateCmd.Parameters.AddWithValue("@Konfession", txtKonferssion.Text)
                        updateCmd.Parameters.AddWithValue("@Konfessionkurz", txtKonferssionKurz.Text)
                        updateCmd.Parameters.AddWithValue("@ID", ID.Value)
                        updateCmd.ExecuteNonQuery()
                        MessageBox.Show("Änderungen gespeichert!")
                    End If
                End Using

                LoadData() ' DataGrid aktualisieren
            Catch ex As Exception
                MessageBox.Show("Fehler beim Speichern: " & ex.Message)
            End Try
        End If
    End Sub

    Private Sub LoadData()
        Try
            Using conn As New OleDbConnection(connectionString)
                conn.Open()
                Dim cmd As New OleDbCommand("SELECT * FROM tblKonfession ORDER BY Konfessionkurz", conn)
                Dim adapter As New OleDbDataAdapter(cmd)
                dt.Clear()
                adapter.Fill(dt)
            End Using

            dgKonfession.ItemsSource = dt.DefaultView

            'With dgKonfession
            '    If .Columns.Count > 0 Then
            '        .Columns(0).Visibility = Visibility.Collapsed ' ID ausblenden
            '    End If
            '    .IsReadOnly = True
            '    .CanUserAddRows = False
            '    .CanUserDeleteRows = False
            'End With
        Catch ex As Exception
            MessageBox.Show("Fehler: " & ex.Message)
        End Try
    End Sub

    Private Sub btnNew_Click(sender As Object, e As RoutedEventArgs) Handles btnNew.Click
        txtKonferssionKurz.Clear()
        txtKonferssion.Clear()
        ID = Nothing
        isNewRecord = True
        txtKonferssionKurz.Focus()
    End Sub


    Private Sub dgKonfession_AutoGeneratedColumns(sender As Object, e As EventArgs) Handles dgKonfession.AutoGeneratedColumns
        For Each col In dgKonfession.Columns
            If col.Header IsNot Nothing AndAlso String.Equals(col.Header.ToString(), "tblKonfessionID", StringComparison.OrdinalIgnoreCase) Then
                col.Visibility = Visibility.Collapsed
            End If
        Next
        dgKonfession.IsReadOnly = True
        dgKonfession.CanUserAddRows = False
        dgKonfession.CanUserDeleteRows = False
    End Sub

    Private Sub btnTest_Click(sender As Object, e As RoutedEventArgs) Handles btnTest.Click
        Dim strDB As String
        Dim cDB As ClsDatabase
        Dim DbVersion As Long
        strDB = My.Settings.DBPath
        cDB = New ClsDatabase(strDB)
        ' cDB.CreateDB()
        'cDB.FillDatabase("D:\Daten\programierung neu\inoGen\inoGenDLL\SQL\db.sql")
        DbVersion = cDB.CheckDBVersion
        'Dim strDBfile As String = Path.GetFileName(strDB)
    End Sub
End Class
