Imports System.Data
Imports System.Data.OleDb

Public Class orte
    Private connectionString As String = String.Format("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=""{0}"";", My.Settings.DBPath)

    Private dt As New DataTable()

    Private isNewRecord As Boolean = False
    Private ID As Integer? = Nothing


    Public Sub New()
        InitializeComponent()

        LoadData()
        LoadKreisListe()
    End Sub

    Private Sub btnSave_Click(sender As Object, e As RoutedEventArgs) Handles btnSave.Click
        Dim rowView As DataRowView = CType(dgOrte.SelectedItem, DataRowView)
        If rowView IsNot Nothing Or isNewRecord Then
            ' Werte in DataRow ändern


            ' Änderungen in Access speichern
            Try
                Using conn As New OleDbConnection(connectionString)
                    conn.Open()
                    If isNewRecord Then
                        Dim insertCmd As New OleDbCommand("INSERT INTO tblOrt (Ort, tblKreisID, Info) VALUES (?, ?, ?)", conn)
                        insertCmd.Parameters.AddWithValue("@Ort", txtOrt.Text)
                        insertCmd.Parameters.AddWithValue("@Kreisid", cbKreis.SelectedValue)
                        insertCmd.Parameters.AddWithValue("@Info", txtInfo.Text)
                        insertCmd.ExecuteNonQuery()
                        MessageBox.Show("Neuer Datensatz gespeichert!")
                    ElseIf ID.HasValue Then
                        Dim updateCmd As New OleDbCommand("UPDATE tblOrt SET Ort = ?, tblKreisID = ?, Info = ? WHERE tblOrtID = ?", conn)
                        updateCmd.Parameters.AddWithValue("@Ort", txtOrt.Text)
                        updateCmd.Parameters.AddWithValue("@Kreisid", cbKreis.SelectedValue)
                        updateCmd.Parameters.AddWithValue("@Info", txtInfo.Text)
                        updateCmd.Parameters.AddWithValue("@ID", ID.Value)
                        updateCmd.ExecuteNonQuery()
                        MessageBox.Show("Änderungen gespeichert!")
                    End If
                End Using

                LoadData()
            Catch ex As Exception
                MessageBox.Show("Fehler beim Speichern: " & ex.Message)
            End Try
        End If
    End Sub

    Private Sub LoadData()
        Try
            Using conn As New OleDbConnection(connectionString)
                conn.Open()
                '  Dim cmd As New OleDbCommand("SELECT * FROM tblOrt ORDER BY Ort", conn)
                Dim cmd As New OleDbCommand("SELECT o.*, k.Kreis FROM tblOrt as o, tblKreis as k WHERE o.tblKreisID = k.tblKreisID ORDER BY o.Ort", conn)
                Dim adapter As New OleDbDataAdapter(cmd)
                dt.Clear()
                adapter.Fill(dt)
            End Using

            dgOrte.ItemsSource = dt.DefaultView

        Catch ex As Exception
            MessageBox.Show("Fehler: " & ex.Message)
        End Try
    End Sub

    Private Sub btnNew_Click(sender As Object, e As RoutedEventArgs) Handles btnNew.Click
        txtOrt.Clear()
        cbKreis.SelectedValue = 1
        txtInfo.Clear()
        ID = Nothing
        isNewRecord = True
        txtOrt.Focus()
    End Sub


    Private Sub dgOrte_AutoGeneratedColumns(sender As Object, e As EventArgs) Handles dgOrte.AutoGeneratedColumns
        For Each col In dgOrte.Columns
            If col.Header IsNot Nothing AndAlso String.Equals(col.Header.ToString(), "tblOrtID", StringComparison.OrdinalIgnoreCase) Then
                col.Visibility = Visibility.Collapsed
            End If
            If col.Header IsNot Nothing AndAlso String.Equals(col.Header.ToString(), "tblKreisID", StringComparison.OrdinalIgnoreCase) Then
                col.Visibility = Visibility.Collapsed
            End If
        Next
        dgOrte.IsReadOnly = True
        dgOrte.CanUserAddRows = False
        dgOrte.CanUserDeleteRows = False
    End Sub

    Private Sub dgOrte_MouseDoubleClick(sender As Object, e As MouseButtonEventArgs)
        Dim rowView As DataRowView = CType(dgOrte.SelectedItem, DataRowView)
        If rowView IsNot Nothing Then
            ID = Convert.ToInt32(rowView("tblOrtID"))
            txtOrt.Text = rowView("Ort").ToString()
            cbKreis.SelectedValue = Convert.ToInt32(rowView("tblKreisID"))
            txtInfo.Text = rowView("Info").ToString()
            isNewRecord = False
        End If
    End Sub

    Private Sub cbKreis_SelectionChanged(sender As Object, e As SelectionChangedEventArgs) Handles cbKreis.SelectionChanged
        If cbKreis.SelectedValue IsNot Nothing Then
            Dim selectedID As Integer = CInt(cbKreis.SelectedValue)
        End If
    End Sub

    Private Sub LoadKreisListe()
        Try
            Dim dt As New DataTable()
            Using conn As New OleDbConnection(connectionString)
                conn.Open()
                Dim cmd As New OleDbCommand("SELECT tblKreisID, Kreis FROM tblKreis ORDER BY Kreis", conn)

                Dim adapter As New OleDbDataAdapter(cmd)
                adapter.Fill(dt)
            End Using

            cbKreis.ItemsSource = dt.DefaultView

        Catch ex As Exception
            MessageBox.Show("Fehler beim Laden der Kreise: " & ex.Message)
        End Try
    End Sub
End Class
