Imports System.Data
Imports inoGenDLL
Imports iText.StyledXmlParser.Jsoup.Select.Evaluator

Public Class QuellenZitatEreignis
    Private ReadOnly _navigation As INavigationService

    Private dt As New DataTable()
    Private cGenDB As New ClsGenDB(My.Settings.DBPath)
    Private ID As Integer? = Nothing
    Private isUCLoaded As Boolean = False

    Private Sub LoadData()


        Try
            dt.Clear()
            dt = cGenDB.GetQuelleZitateEvents(ID)

            dgQuellZitatEreignis.ItemsSource = dt.DefaultView

        Catch ex As Exception
            MessageBox.Show("Fehler: " & ex.Message)
        End Try



    End Sub

    Public Sub New(ID As Integer?, navigation As INavigationService)
        InitializeComponent()
        _navigation = navigation

        Me.ID = ID

        LoadData()

    End Sub

    Private Sub dgQuellZitatEreignis_AutoGeneratedColumns(
    sender As Object,
    e As EventArgs
) Handles dgQuellZitatEreignis.AutoGeneratedColumns

        Dim jahrConverter As New ClsJahrBackgroundConverter()



        For i As Integer = dgQuellZitatEreignis.Columns.Count - 1 To 0 Step -1

            Dim col As DataGridColumn = dgQuellZitatEreignis.Columns(i)

            If col.Header Is Nothing Then Continue For

            Dim header As String = col.Header.ToString()

            ' =========================================================
            ' ID-SPALTEN AUSBLENDEN
            ' =========================================================
            'If String.Equals(header, "tblQuellZitatID", StringComparison.OrdinalIgnoreCase) _
            If String.Equals(header, "tblQuelleID", StringComparison.OrdinalIgnoreCase) _
            OrElse String.Equals(header, "tblEreignisArtID", StringComparison.OrdinalIgnoreCase) _
            OrElse String.Equals(header, "Anzahl", StringComparison.OrdinalIgnoreCase) _
            OrElse String.Equals(header, "tblFamilieID", StringComparison.OrdinalIgnoreCase) _
            OrElse String.Equals(header, "tblPersonID", StringComparison.OrdinalIgnoreCase) _
            OrElse String.Equals(header, "tblEreignisID", StringComparison.OrdinalIgnoreCase) _
            OrElse String.Equals(header, "active", StringComparison.OrdinalIgnoreCase) Then

                col.Visibility = Visibility.Collapsed


                ' =========================================================
                ' JAHR
                ' =========================================================
            ElseIf String.Equals(header, "tblQuellZitatID", StringComparison.OrdinalIgnoreCase) And isUCLoaded = False Then

                Dim index As Integer = i

                dgQuellZitatEreignis.Columns.RemoveAt(i)

                Dim jahrColumn As New DataGridTemplateColumn()
                jahrColumn.Header = "ID"

                ' -----------------------------------------------------
                ' Border für Hintergrundfarbe
                ' -----------------------------------------------------
                Dim borderFactory As New FrameworkElementFactory(
                GetType(Border))

                borderFactory.SetBinding(
                Border.BackgroundProperty,
                New Binding("Anzahl") With {
                    .Converter = jahrConverter
                })

                ' -----------------------------------------------------
                ' Jahr anzeigen
                ' -----------------------------------------------------
                Dim textFactory As New FrameworkElementFactory(
                GetType(TextBlock))

                textFactory.SetBinding(
                TextBlock.TextProperty,
                New Binding("tblQuellZitatID"))

                textFactory.SetValue(
                TextBlock.VerticalAlignmentProperty,
                VerticalAlignment.Center)

                textFactory.SetValue(
                TextBlock.MarginProperty,
                New Thickness(4, 0, 4, 0))

                borderFactory.AppendChild(textFactory)

                Dim jahrTemplate As New DataTemplate()
                jahrTemplate.VisualTree = borderFactory

                jahrColumn.CellTemplate = jahrTemplate

                dgQuellZitatEreignis.Columns.Insert(index, jahrColumn)


                ' =========================================================
                ' DATUM
                ' =========================================================
            ElseIf String.Equals(header, "QDatum", StringComparison.OrdinalIgnoreCase) Then
                If isUCLoaded = False Then
                    Dim index As Integer = i

                    dgQuellZitatEreignis.Columns.RemoveAt(i)

                    Dim datumColumn As New DataGridTemplateColumn()
                    datumColumn.Header = "QDatum "

                    ' -----------------------------------------------------
                    ' Anzeige
                    ' -----------------------------------------------------
                    Dim textFactory As New FrameworkElementFactory(
                GetType(TextBlock))

                    textFactory.SetBinding(
                TextBlock.TextProperty,
                New Binding("QDatum") With {
                    .StringFormat = "dd.MM.yyyy"
                })

                    textFactory.SetValue(
                TextBlock.VerticalAlignmentProperty,
                VerticalAlignment.Center)

                    textFactory.SetValue(
                TextBlock.MarginProperty,
                New Thickness(4, 0, 4, 0))

                    Dim displayTemplate As New DataTemplate()
                    displayTemplate.VisualTree = textFactory

                    datumColumn.CellTemplate = displayTemplate

                    ' -----------------------------------------------------
                    ' Bearbeiten → DatePicker
                    ' -----------------------------------------------------
                    Dim datePickerFactory As New FrameworkElementFactory(
                GetType(DatePicker))

                    datePickerFactory.SetBinding(
                DatePicker.SelectedDateProperty,
                New Binding("QDatum") With {
                    .Mode = BindingMode.TwoWay,
                    .UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged
                })

                    datePickerFactory.SetValue(
                DatePicker.VerticalAlignmentProperty,
                VerticalAlignment.Center)

                    datePickerFactory.SetValue(
                DatePicker.MarginProperty,
                New Thickness(0))

                    Dim editTemplate As New DataTemplate()
                    editTemplate.VisualTree = datePickerFactory

                    datumColumn.CellEditingTemplate = editTemplate

                    dgQuellZitatEreignis.Columns.Insert(index, datumColumn)
                Else
                    col.Visibility = Visibility.Collapsed
                End If

            ElseIf String.Equals(header, "EDatum", StringComparison.OrdinalIgnoreCase) Then
                If isUCLoaded = False Then
                    Dim index As Integer = i

                    dgQuellZitatEreignis.Columns.RemoveAt(i)

                    Dim datumColumn As New DataGridTemplateColumn()
                    datumColumn.Header = "EDatum "

                    ' -----------------------------------------------------
                    ' Anzeige
                    ' -----------------------------------------------------
                    Dim textFactory As New FrameworkElementFactory(
                GetType(TextBlock))

                    textFactory.SetBinding(
                TextBlock.TextProperty,
                New Binding("EDatum") With {
                    .StringFormat = "dd.MM.yyyy"
                })

                    textFactory.SetValue(
                TextBlock.VerticalAlignmentProperty,
                VerticalAlignment.Center)

                    textFactory.SetValue(
                TextBlock.MarginProperty,
                New Thickness(4, 0, 4, 0))

                    Dim displayTemplate As New DataTemplate()
                    displayTemplate.VisualTree = textFactory

                    datumColumn.CellTemplate = displayTemplate

                    ' -----------------------------------------------------
                    ' Bearbeiten → DatePicker
                    ' -----------------------------------------------------
                    Dim datePickerFactory As New FrameworkElementFactory(
                GetType(DatePicker))

                    datePickerFactory.SetBinding(
                DatePicker.SelectedDateProperty,
                New Binding("EDatum") With {
                    .Mode = BindingMode.TwoWay,
                    .UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged
                })

                    datePickerFactory.SetValue(
                DatePicker.VerticalAlignmentProperty,
                VerticalAlignment.Center)

                    datePickerFactory.SetValue(
                DatePicker.MarginProperty,
                New Thickness(0))

                    Dim editTemplate As New DataTemplate()
                    editTemplate.VisualTree = datePickerFactory

                    datumColumn.CellEditingTemplate = editTemplate

                    dgQuellZitatEreignis.Columns.Insert(index, datumColumn)
                Else
                    col.Visibility = Visibility.Collapsed
                End If

                ' =========================================================
                ' INTERNETADRESSE
                ' =========================================================
            ElseIf String.Equals(header, "InternetAdresse", StringComparison.OrdinalIgnoreCase) And isUCLoaded = False Then

                Dim index As Integer = i

                dgQuellZitatEreignis.Columns.RemoveAt(i)

                Dim linkColumn As New DataGridTemplateColumn()
                linkColumn.Header = "Internetadresse"

                ' -----------------------------------------------------
                ' Hyperlink
                ' -----------------------------------------------------
                Dim textBlockFactory As New FrameworkElementFactory(
                GetType(TextBlock))

                Dim hyperlinkFactory As New FrameworkElementFactory(
                GetType(Hyperlink))

                hyperlinkFactory.SetBinding(
                Hyperlink.NavigateUriProperty,
                New Binding("InternetAdresse"))

                hyperlinkFactory.SetBinding(
                Hyperlink.CommandProperty,
                New Binding("DataContext.OpenUrlCommand") With {
                    .RelativeSource = New RelativeSource(
                        RelativeSourceMode.FindAncestor,
                        GetType(DataGrid),
                        1)
                })

                Dim linkTextFactory As New FrameworkElementFactory(
                GetType(Run))

                linkTextFactory.SetBinding(
                Run.TextProperty,
                New Binding("InternetAdresse"))

                hyperlinkFactory.AppendChild(linkTextFactory)
                textBlockFactory.AppendChild(hyperlinkFactory)

                textBlockFactory.SetValue(
                TextBlock.VerticalAlignmentProperty,
                VerticalAlignment.Center)

                textBlockFactory.SetValue(
                TextBlock.MarginProperty,
                New Thickness(4, 0, 4, 0))

                Dim linkTemplate As New DataTemplate()
                linkTemplate.VisualTree = textBlockFactory

                linkColumn.CellTemplate = linkTemplate

                dgQuellZitatEreignis.Columns.Insert(index, linkColumn)

            End If

        Next

        dgQuellZitatEreignis.CanUserAddRows = False
        dgQuellZitatEreignis.CanUserDeleteRows = False

        isUCLoaded = True

    End Sub

    Private Sub dgQuellZitatEreignis_MouseDoubleClick(sender As Object, e As MouseButtonEventArgs) Handles dgQuellZitatEreignis.MouseDoubleClick
        Dim rowView As DataRowView = CType(dgQuellZitatEreignis.SelectedItem, DataRowView)
        Dim PID As Integer
        Dim FID As Integer
        If rowView IsNot Nothing Then
            FID = Convert.ToInt32(rowView("tblFamilieID"))

            PID = Convert.ToInt32(rowView("tblPersonID"))

            If FID > 0 Then
                _navigation.NavigateTo(eNavigationType.Familie, FID)
            Else
                _navigation.NavigateTo(eNavigationType.Person, PID)
            End If

        End If
    End Sub
End Class
