Imports System.Data
Imports System.Data.OleDb
Imports inoGenDLL
Imports iText.StyledXmlParser.Jsoup.Select.Evaluator
Imports Windows.Win32.System

Public Class Quellen
    Private connectionString As String = String.Format("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=""{0}"";", My.Settings.DBPath)

    Private dt As New DataTable()

    Private isNewRecord As Boolean = False
    Private ID As Integer? = Nothing

    Private cGenDB As New ClsGenDB(My.Settings.DBPath)

    Private Sub btnDelete_Click(sender As Object, e As RoutedEventArgs)

    End Sub

    Private Sub btnNew_Click(sender As Object, e As RoutedEventArgs)
        txtQuelle.Clear()
        txtQuelleKurz.Clear()
        txtInfo.Clear()
        ID = Nothing
        isNewRecord = True
        txtQuelle.Focus()
    End Sub

    Private Sub btnSave_Click(sender As Object, e As RoutedEventArgs) Handles btnSave.Click
        Dim rowView As DataRowView = CType(dgQuellen.SelectedItem, DataRowView)
        If rowView IsNot Nothing Or isNewRecord Then

            Try

                If isNewRecord Then
                    ID = cGenDB.SetQuelle(txtQuelle.Text, txtQuelleKurz.Text, txtInfo.Text)
                    isNewRecord = False
                    MessageBox.Show("Neuer Datensatz gespeichert!")
                ElseIf ID.HasValue Then
                    cGenDB.UpdateQuelle(ID.Value, txtQuelle.Text, txtQuelleKurz.Text, txtInfo.Text)
                    MessageBox.Show("Änderungen gespeichert!")
                End If
                LoadData()
            Catch ex As Exception
                MessageBox.Show("Fehler beim Speichern: " & ex.Message)
            End Try
        End If
    End Sub

    Private Sub LoadData()
        Try
            dt.Clear()
            dt = cGenDB.GetQuellen

            dgQuellen.ItemsSource = dt.DefaultView

        Catch ex As Exception
            MessageBox.Show("Fehler: " & ex.Message)
        End Try

        If ID.HasValue Then
            For Each rowView As DataRowView In dgQuellen.Items
                If CInt(rowView("tblQuelleID")) = ID Then
                    ' Selektion setzen
                    dgQuellen.SelectedItem = rowView

                    ' Sichtbar machen
                    dgQuellen.ScrollIntoView(rowView)

                    Exit For
                End If
            Next
        End If
    End Sub

    Public Sub New()
        InitializeComponent()

        LoadData()
        isNewRecord = True
    End Sub

    Private Sub dgQuellen_AutoGeneratedColumns(sender As Object, e As EventArgs) Handles dgQuellen.AutoGeneratedColumns
        For Each col In dgQuellen.Columns
            If col.Header IsNot Nothing AndAlso String.Equals(col.Header.ToString(), "tblQuelleID", StringComparison.OrdinalIgnoreCase) Then
                col.Visibility = Visibility.Collapsed
            End If
            If col.Header IsNot Nothing AndAlso String.Equals(col.Header.ToString(), "active", StringComparison.OrdinalIgnoreCase) Then
                col.Visibility = Visibility.Collapsed
            End If
        Next
        dgQuellen.IsReadOnly = True
        dgQuellen.CanUserAddRows = False
        dgQuellen.CanUserDeleteRows = False
    End Sub

    Private Sub dgQuellen_MouseDoubleClick(sender As Object, e As MouseButtonEventArgs)
        Dim rowView As DataRowView = CType(dgQuellen.SelectedItem, DataRowView)
        If rowView IsNot Nothing Then
            ID = Convert.ToInt32(rowView("tblQuelleID"))
            txtQuelle.Text = rowView("Quelle").ToString()
            txtQuelleKurz.Text = rowView("QuelleKurz").ToString
            txtInfo.Text = rowView("QuelleBeschreibung").ToString()
            isNewRecord = False
        End If
    End Sub
End Class
