Imports System.Data
Imports System.Data.OleDb
Imports inoGenDLL
Imports iText.StyledXmlParser.Jsoup.Select.Evaluator

Public Class Statistics
    Private connectionString As String =
   String.Format("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=""{0}"";", My.Settings.DBPath)

    Private VKHTotal As Integer

    Private cGDB As New ClsGenDB(My.Settings.DBPath)

    Private VKHOrt As String
    Private Sub CloseButton_Click(sender As Object, e As RoutedEventArgs)
        Close()
    End Sub

    Private Sub Statistics_Initialized(sender As Object, e As EventArgs) Handles Me.Initialized
        If Not IsNothing(My.Settings.CurrentWork) Then
            Dim i As Integer = 1
            For Each entry In My.Settings.CurrentWork
                If entry.StartsWith("VKHOrt:") Then
                    VKHOrt = entry.Replace("VKHOrt:", "")
                    Exit For
                End If
            Next
        End If
        CommonData()
        VKHData()
    End Sub

    Private Sub CommonData()
        A1.Content = "Vornamen gesamt: " & Format(cGDB.StatisicsVornamen, "#,##0")
        A2.Content = "Nachnamen gesamt: " & Format(cGDB.StatisicsNachnamen, "#,##0")
        A3.Content = "Orte gesamt: " & Format(cGDB.StatisicsOrte, "#,##0")
        A4.Content = "Personen gesamt: " & Format(cGDB.StatisicsPersonen, "#,##0")
        A5.Content = "Familien gesamt: " & Format(cGDB.StatisicsFamilien, "#,##0")
    End Sub

    Private Sub VKHData()
        Dim dt As DataTable = cGDB.StatisicsVKHeirat
        Dim dtOE As DataTable = cGDB.StatisticsVKHLocationsExtern(VKHOrt, "")
        With dt.Rows(0)
            VKHTotal = .Item(0)
            H1.Content = "Einträge gesamt: " & Format(.Item(0), "#,##0")
            H2.Content = "Bräutigame gesamt: " & Format(.Item(1), "#,##0")
            H3.Content = "Väter des Bräutigams gesamt: " & Format(.Item(2), "#,##0")
            H4.Content = "Mütter des Bräutigams gesamt: " & Format(.Item(3), "#,##0")
            H5.Content = "Bräute gesamt: " & Format(.Item(4), "#,##0")
            H6.Content = "Väter der Braut gesamt: " & Format(.Item(5), "#,##0")
            H7.Content = "Mütter des Braut gesamt: " & Format(.Item(6), "#,##0")
            H8.Content = "Personen gesamt: " & Format(.Item(1) + .Item(2) + .Item(3) + .Item(4) + .Item(5) + .Item(6), "#,##0")
            H9.Content = "Zeugen gesamt: " & Format(.Item(7) + .Item(8) + .Item(9) + .Item(10), "#,##0")
            H10.Content = String.Format("Heiraten in anderen Orten: {0} ({1})", Format(dtOE.Rows.Count, "#,##0"), Format(dtOE.Rows.Count / VKHTotal, "0.00%"))

        End With

        With dgVKHYears
            .ItemsSource = cGDB.StatisticsVKHYears.DefaultView
            .IsReadOnly = True
            .CanUserAddRows = False
            .CanUserDeleteRows = False
        End With

        With dgVKHPages
            .ItemsSource = cGDB.StatisticsVKHPages.DefaultView
            .IsReadOnly = True
            .CanUserAddRows = False
            .CanUserDeleteRows = False
        End With

        UpdateCounts()
    End Sub

    Private Sub UpdateCounts()
        If dgVKHYears.ItemsSource IsNot Nothing Then
            txtYearsCount.Text = String.Format("Zeilen: {0} Ø {1}", dgVKHYears.Items.Count, Format(VKHTotal / dgVKHYears.Items.Count, "#,##0.00"))
        End If

        If dgVKHPages.ItemsSource IsNot Nothing Then
            txtPagesCount.Text = String.Format("Zeilen: {0} Ø {1}", dgVKHPages.Items.Count, Format(VKHTotal / dgVKHPages.Items.Count, "#,##0.00"))
        End If
    End Sub

    Private Sub dgVKHPages_AutoGeneratedColumns(sender As Object, e As EventArgs) Handles dgVKHPages.AutoGeneratedColumns
        For Each col In dgVKHPages.Columns
            If col.Header?.ToString() = "SeiteH" OrElse col.Header?.ToString() = "Anzahl" Then
                Dim textCol = TryCast(col, DataGridTextColumn)
                If textCol IsNot Nothing Then
                    Dim style As New Style(GetType(TextBlock))
                    style.Setters.Add(New Setter(TextBlock.TextAlignmentProperty, TextAlignment.Right))
                    style.Setters.Add(New Setter(TextBlock.HorizontalAlignmentProperty, HorizontalAlignment.Right))
                    textCol.ElementStyle = style
                End If
            End If
        Next
    End Sub

    Private Sub dgVKHYears_AutoGeneratedColumns(sender As Object, e As EventArgs) Handles dgVKHYears.AutoGeneratedColumns
        For Each col In dgVKHYears.Columns
            If col.Header?.ToString() = "Jahr" OrElse col.Header?.ToString() = "Anzahl" Then
                Dim textCol = TryCast(col, DataGridTextColumn)
                If textCol IsNot Nothing Then
                    Dim style As New Style(GetType(TextBlock))
                    style.Setters.Add(New Setter(TextBlock.TextAlignmentProperty, TextAlignment.Right))
                    style.Setters.Add(New Setter(TextBlock.HorizontalAlignmentProperty, HorizontalAlignment.Right))
                    textCol.ElementStyle = style
                End If
            End If
        Next
    End Sub
End Class
