Imports System.Data
Imports System.Data.OleDb
Imports inoGenDLL
Imports iText.StyledXmlParser.Jsoup.[Select].Evaluator

Public Class VKH_Übernahme
    Private connectionString As String =
   String.Format("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=""{0}"";", My.Settings.DBPath)

    Private dt As New DataTable()

    Private isNewRecord As Boolean = False
    Private ID As Integer? = Nothing
    Private testDate As String

    Private pSQL As String = "SELECT
            *
        FROM
            tblVKH"

    Private cDB As New clsDB(My.Settings.DBPath)
    Private cGDB As New ClsGenDB(My.Settings.DBPath)
    Private cGH As New ClsGenHelper

    Private NT As String = "____"
    Private VT As String = "____"
    Private DaT As String = "0000"

    Public Event PersonenUebergabe As EventHandler(Of PersonenUebergabeEventArgs)
    Public Event PersonRueckgabe As EventHandler(Of PersonRueckgabeEventArgs)

    Public Enum PersonTyp
        Leer
        K
        V
        M
        Btg
        VBtg
        MBtg
        Bt
        VBt
        MBt
        Z1
        Z2
        Z3
        Z4
    End Enum

    Public PType As PersonTyp

    Dim CurrentIDs As New Dictionary(Of PersonTyp, Integer)

    Public Sub New()
        InitializeComponent()

        'If My.Settings.LastVKHID > 0 Then
        '    ID = My.Settings.LastVKHID
        '    FillEntry(ID)
        'Else
        '    btnNew_Click(Nothing, Nothing)
        'End If

        LoadData()

        'ckbAutoCorrect.IsChecked = True
        AddHandler Me.Loaded, AddressOf OnLoaded
    End Sub

    Private Sub OnLoaded(sender As Object, e As RoutedEventArgs)

        'RaiseEvent RequestResizeMainWindow(1300)
    End Sub
    Private Sub dgEintrag_AutoGeneratedColumns(sender As Object, e As EventArgs) Handles dgEintrag.AutoGeneratedColumns
        For Each col In dgEintrag.Columns
            If col.Header IsNot Nothing Then
                Select Case col.Header.ToString()
                    Case "SEITE_H", "NR_H", "VN_BR", "FN_BR", "VN_BT", "FN_BT"
                    Case "HDatum"
                        Dim textCol = TryCast(col, DataGridTextColumn)
                        If textCol IsNot Nothing Then
                            Dim oldBinding = TryCast(textCol.Binding, Binding)
                            If oldBinding IsNot Nothing Then
                                textCol.Binding = New Binding(oldBinding.Path.Path) With {
                                    .StringFormat = "dd.MM.yyyy"
                                }
                            End If
                        End If
                    Case Else
                        col.Visibility = Visibility.Collapsed
                End Select
            End If
        Next

        dgEintrag.IsReadOnly = True
        dgEintrag.CanUserAddRows = False
        dgEintrag.CanUserDeleteRows = False
    End Sub

    Private Sub dgEintrag_MouseDoubleClick(sender As Object, e As MouseButtonEventArgs)
        Dim rowView As DataRowView = CType(dgEintrag.SelectedItem, DataRowView)
        If rowView IsNot Nothing Then
            ID = Convert.ToInt32(rowView("tblVKHID"))
            FillEntry(ID)
        End If

    End Sub

    Private Sub LoadData()
        Dim strSQL As String = pSQL & " ORDER BY BUCH_H, SEITE_H, NR_H"


        Try
            Using conn As New OleDbConnection(connectionString)
                conn.Open()
                Dim cmd As New OleDbCommand(strSQL, conn)
                Dim adapter As New OleDbDataAdapter(cmd)
                dt.Clear()
                adapter.Fill(dt)
            End Using

            dgEintrag.ItemsSource = dt.DefaultView

        Catch ex As Exception
            MessageBox.Show("Fehler: " & ex.Message)
        End Try

        If ID.HasValue Then
            For Each rowView As DataRowView In dgEintrag.Items
                If CInt(rowView("tblVKHID")) = ID Then
                    ' Selektion setzen
                    dgEintrag.SelectedItem = rowView

                    ' Sichtbar machen
                    dgEintrag.ScrollIntoView(rowView)

                    Exit For
                End If
            Next
        End If
    End Sub

    Private Sub FillEntry(EID As Integer)
        Using conn As New OleDbConnection(connectionString)
            conn.Open()
            ClearAllTextBoxes(Me)
            ResetAllButtonsBackground(Me, True)
            Dim sql As String = pSQL & " WHERE tblVKHID = ?"
            Using cmd As New OleDbCommand(sql, conn)
                cmd.Parameters.AddWithValue("@p1", EID)

                Using reader As OleDbDataReader = cmd.ExecuteReader()
                    If reader.Read() Then
                        ' Werte auslesen und prüfen auf DBNull
                        If Not IsDBNull(reader("BUCH_H")) Then
                            txtQuelle.Text = reader("BUCH_H")
                        End If

                        If Not IsDBNull(reader("SEITE_H")) Then
                            txtSeite.Text = reader("SEITE_H")
                        End If

                        If Not IsDBNull(reader("NR_H")) Then
                            txtNr.Text = reader("NR_H")
                        End If

                        If Not IsDBNull(reader("HDatum")) Then
                            txtHDatum.Text = reader("HDatum")
                            DaT = Year(txtHDatum.Text)
                        End If

                        If Not IsDBNull(reader("DimDatum")) Then
                            txtDimDatum.Text = reader("DimDatum")
                        End If

                        If Not IsDBNull(reader("OnlineReference")) Then
                            txtURL.Text = reader("OnlineReference")
                        End If
                        If Not IsDBNull(reader("ReferenceDetails")) Then
                            txtQuelleSeite.Text = reader("ReferenceDetails")
                        End If


                        ID = EID
                        isNewRecord = False
                        PType = PersonTyp.Leer
                        CurrentIDs.Clear()


                        If Not IsDBNull(reader("VN_BR")) Then
                            btnBtg.IsEnabled = IIf(reader("VN_BR") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("FN_BR")) Then
                            btnBtg.IsEnabled = IIf(reader("FN_BR") <> "", True, False)
                        End If
                        'If Not IsDBNull(reader("GebDatum_BR")) Then
                        '    '   btnBtg.IsEnabled = IIf(reader("GebDatum_BR") <> "", True, False)
                        'End If
                        If Not IsDBNull(reader("W_BR")) Then
                            btnBtg.IsEnabled = IIf(reader("W_BR") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("H_BR")) Then
                            btnBtg.IsEnabled = IIf(reader("H_BR") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("Z_BR")) Then
                            btnBtg.IsEnabled = IIf(reader("Z_BR") <> "", True, False)
                        End If

                        If Not IsDBNull(reader("VN_VBR")) Then
                            btnVBtg.IsEnabled = IIf(reader("VN_VBR") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("FN_VBR")) Then
                            btnVBtg.IsEnabled = IIf(reader("FN_VBR") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("Z_VBR")) Then
                            btnVBtg.IsEnabled = IIf(reader("Z_VBR") <> "", True, False)
                        End If

                        If Not IsDBNull(reader("VN_MBR")) Then
                            btnMBtg.IsEnabled = IIf(reader("VN_MBR") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("FN_MBR")) Then
                            btnMBtg.IsEnabled = IIf(reader("FN_MBR") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("Z_MBR")) Then
                            btnMBtg.IsEnabled = IIf(reader("Z_MBR") <> "", True, False)
                        End If
                        'If Not IsDBNull(reader("W_EBR")) Then
                        '    btnVBtg.IsEnabled = True
                        'End If

                        If Not IsDBNull(reader("VN_BT")) Then
                            btnBt.IsEnabled = IIf(reader("VN_BT") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("FN_BT")) Then
                            btnBt.IsEnabled = IIf(reader("FN_BT") <> "", True, False)
                        End If
                        'If Not IsDBNull(reader("GebDatum_BT")) Then
                        '    btnBt.IsEnabled = True
                        'End If
                        If Not IsDBNull(reader("W_BT")) Then
                            btnBt.IsEnabled = IIf(reader("W_BT") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("H_BT")) Then
                            btnBt.IsEnabled = IIf(reader("H_BT") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("Z_BT")) Then
                            btnBt.IsEnabled = IIf(reader("Z_BT") <> "", True, False)
                        End If

                        If Not IsDBNull(reader("VN_VBT")) Then
                            btnVBt.IsEnabled = IIf(reader("VN_VBT") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("FN_VBT")) Then
                            btnVBt.IsEnabled = IIf(reader("FN_VBT") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("Z_VBT")) Then
                            btnVBt.IsEnabled = IIf(reader("Z_VBT") <> "", True, False)
                        End If

                        If Not IsDBNull(reader("VN_MBT")) Then
                            btnMBt.IsEnabled = IIf(reader("VN_MBT") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("FN_MBT")) Then
                            btnMBt.IsEnabled = IIf(reader("FN_MBT") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("Z_MBT")) Then
                            btnMBt.IsEnabled = IIf(reader("Z_MBT") <> "", True, False)
                        End If
                        'If Not IsDBNull(reader("W_EBT")) Then
                        '    txtWEBt.Text = reader("W_EBT")
                        'End If

                        If Not IsDBNull(reader("ANM_H")) Then
                            txtInfo.Text = reader("ANM_H")
                        End If

                        If Not IsDBNull(reader("VN_HZ1")) Then
                            btnZ1.IsEnabled = IIf(reader("VN_HZ1") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("FN_HZ1")) Then
                            btnZ1.IsEnabled = IIf(reader("FN_HZ1") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("G_HZ1")) Then
                            btnZ1.IsEnabled = IIf(reader("G_HZ1") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("Z_HZ1")) Then
                            btnZ1.IsEnabled = IIf(reader("Z_HZ1") <> "", True, False)
                        End If

                        If Not IsDBNull(reader("VN_HZ2")) Then
                            btnZ2.IsEnabled = IIf(reader("VN_HZ2") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("FN_HZ2")) Then
                            btnZ2.IsEnabled = IIf(reader("FN_HZ2") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("G_HZ2")) Then
                            btnZ2.IsEnabled = IIf(reader("G_HZ2") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("Z_HZ2")) Then
                            btnZ2.IsEnabled = IIf(reader("Z_HZ2") <> "", True, False)
                        End If

                        If Not IsDBNull(reader("VN_HZ3")) Then
                            btnZ3.IsEnabled = IIf(reader("VN_HZ3") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("FN_HZ3")) Then
                            btnZ3.IsEnabled = IIf(reader("FN_HZ3") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("G_HZ3")) Then
                            btnZ3.IsEnabled = IIf(reader("G_HZ3") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("Z_HZ3")) Then
                            btnZ3.IsEnabled = IIf(reader("Z_HZ3") <> "", True, False)
                        End If

                        If Not IsDBNull(reader("VN_HZ4")) Then
                            btnZ4.IsEnabled = IIf(reader("VN_HZ4") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("FN_HZ4")) Then
                            btnZ4.IsEnabled = IIf(reader("FN_HZ4") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("G_HZ4")) Then
                            btnZ4.IsEnabled = IIf(reader("G_HZ4") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("Z_HZ4")) Then
                            btnZ4.IsEnabled = IIf(reader("Z_HZ4") <> "", True, False)
                        End If

                        txtIndexH.Text = cGH.GetIndexString(reader("FN_BR")) & cGH.GetIndexString(reader("FN_BT")) & DaT
                        DaT = "0000"
                        txtIndexBtg.Text = cGH.GetIndexString(reader("FN_VBR")) & cGH.GetIndexString(reader("FN_MBR")) & DaT
                        txtIndexBt.Text = cGH.GetIndexString(reader("FN_VBT")) & cGH.GetIndexString(reader("FN_MBT")) & DaT
                    Else
                        MessageBox.Show("Kein Eintrag mit dieser ID gefunden.")
                    End If
                End Using
            End Using
        End Using

    End Sub

    Public Sub ClearAllTextBoxes(parent As DependencyObject)
        For i As Integer = 0 To VisualTreeHelper.GetChildrenCount(parent) - 1
            Dim child As DependencyObject = VisualTreeHelper.GetChild(parent, i)

            If TypeOf child Is TextBox Then
                DirectCast(child, TextBox).Clear()
            Else
                ClearAllTextBoxes(child)
            End If
        Next

    End Sub

    Private Sub btnBt_Click(sender As Object, e As RoutedEventArgs) Handles btnBt.Click
        Using conn As New OleDbConnection(connectionString)
            conn.Open()
            ResetAllButtonsBackground(Me)
            DaT = "0000"
            Dim sql As String = pSQL & " WHERE tblVKHID = ?"
            Using cmd As New OleDbCommand(sql, conn)
                cmd.Parameters.AddWithValue("@p1", ID)

                Using reader As OleDbDataReader = cmd.ExecuteReader()
                    If reader.Read() Then
                        If Not IsDBNull(reader("VN_BT")) Then
                            txtV.Text = reader("VN_BT")
                        End If

                        If Not IsDBNull(reader("FN_BT")) Then
                            txtN.Text = reader("FN_BT")
                        End If
                        If Not IsDBNull(reader("GebDatum_BT")) Then
                            txtGeb.Text = reader("GebDatum_BT")
                            DaT = Year(txtGeb.Text)
                        End If
                        If Not IsDBNull(reader("W_BT")) Then
                            txtWO.Text = reader("W_BT")
                        End If
                        If Not IsDBNull(reader("H_BT")) Then
                            txtHO.Text = reader("H_BT")
                        End If
                        If Not IsDBNull(reader("Z_BT")) Then
                            txtZu.Text = reader("Z_BT")
                        End If
                        txtSex.Text = ""
                        lblVTag.Text = cGH.GetIndexString(reader("FN_BT")) & cGH.GetIndexString(reader("VN_BT")) & DaT
                        btnBt.Background = Brushes.LightGreen
                        PType = PersonTyp.Bt
                    Else
                        MessageBox.Show("Kein Eintrag mit dieser ID gefunden.")
                    End If
                End Using
            End Using
        End Using
    End Sub

    Private Sub btnBtg_Click(sender As Object, e As RoutedEventArgs) Handles btnBtg.Click
        Using conn As New OleDbConnection(connectionString)
            conn.Open()
            ResetAllButtonsBackground(Me)
            DaT = "0000"
            Dim sql As String = pSQL & " WHERE tblVKHID = ?"
            Using cmd As New OleDbCommand(sql, conn)
                cmd.Parameters.AddWithValue("@p1", ID)

                Using reader As OleDbDataReader = cmd.ExecuteReader()
                    If reader.Read() Then
                        If Not IsDBNull(reader("VN_BR")) Then
                            txtV.Text = reader("VN_BR")
                        End If

                        If Not IsDBNull(reader("FN_BR")) Then
                            txtN.Text = reader("FN_BR")
                        End If
                        If Not IsDBNull(reader("GebDatum_BR")) Then
                            txtGeb.Text = reader("GebDatum_BR")
                            DaT = Year(txtGeb.Text)
                        End If
                        If Not IsDBNull(reader("W_BR")) Then
                            txtWO.Text = reader("W_BR")
                        End If
                        If Not IsDBNull(reader("H_BR")) Then
                            txtHO.Text = reader("H_BR")
                        End If
                        If Not IsDBNull(reader("Z_BR")) Then
                            txtZu.Text = reader("Z_BR")
                        End If
                        txtSex.Text = ""
                        lblVTag.Text = cGH.GetIndexString(reader("FN_BR")) & cGH.GetIndexString(reader("VN_BR")) & DaT
                        btnBtg.Background = Brushes.LightGreen
                        PType = PersonTyp.Btg
                    Else
                        MessageBox.Show("Kein Eintrag mit dieser ID gefunden.")
                    End If
                End Using
            End Using
        End Using
    End Sub

    Private Sub ResetAllButtonsBackground(root As DependencyObject, Optional blnAll As Boolean = False)

        For i As Integer = 0 To VisualTreeHelper.GetChildrenCount(root) - 1
            Dim child = VisualTreeHelper.GetChild(root, i)

            If TypeOf child Is Button Then
                Dim btn = DirectCast(child, Button)
                btn.ClearValue(Button.BackgroundProperty)
                If blnAll Then
                    btn.IsEnabled = False
                End If
            End If

            ' Rekursiv weitergehen
            ResetAllButtonsBackground(child)
        Next

    End Sub

    Private Sub btnMBt_Click(sender As Object, e As RoutedEventArgs) Handles btnMBt.Click
        Using conn As New OleDbConnection(connectionString)
            conn.Open()
            ResetAllButtonsBackground(Me)
            DaT = "0000"
            Dim sql As String = pSQL & " WHERE tblVKHID = ?"
            Using cmd As New OleDbCommand(sql, conn)
                cmd.Parameters.AddWithValue("@p1", ID)

                Using reader As OleDbDataReader = cmd.ExecuteReader()
                    If reader.Read() Then
                        If Not IsDBNull(reader("VN_MBT")) Then
                            txtV.Text = reader("VN_MBT")
                        End If
                        If Not IsDBNull(reader("FN_MBT")) Then
                            txtN.Text = reader("FN_MBT")
                        End If

                        If Not IsDBNull(reader("W_EBT")) Then
                            txtWO.Text = reader("W_EBT")
                        End If

                        txtGeb.Text = ""
                        txtHO.Text = ""

                        If Not IsDBNull(reader("Z_MBT")) Then
                            txtZu.Text = reader("Z_MBT")
                        End If
                        txtSex.Text = ""
                        lblVTag.Text = cGH.GetIndexString(reader("FN_MBT")) & cGH.GetIndexString(reader("VN_MBT")) & DaT
                        btnMBt.Background = Brushes.LightGreen
                        PType = PersonTyp.MBt
                    Else
                        MessageBox.Show("Kein Eintrag mit dieser ID gefunden.")
                    End If
                End Using
            End Using
        End Using
    End Sub

    Private Sub btnMBtg_Click(sender As Object, e As RoutedEventArgs) Handles btnMBtg.Click
        Using conn As New OleDbConnection(connectionString)
            conn.Open()
            ResetAllButtonsBackground(Me)
            DaT = "0000"
            Dim sql As String = pSQL & " WHERE tblVKHID = ?"
            Using cmd As New OleDbCommand(sql, conn)
                cmd.Parameters.AddWithValue("@p1", ID)

                Using reader As OleDbDataReader = cmd.ExecuteReader()
                    If reader.Read() Then
                        If Not IsDBNull(reader("VN_MBR")) Then
                            txtV.Text = reader("VN_MBR")
                        End If
                        If Not IsDBNull(reader("FN_MBR")) Then
                            txtN.Text = reader("FN_MBR")
                        End If

                        If Not IsDBNull(reader("W_EBR")) Then
                            txtWO.Text = reader("W_EBR")
                        End If

                        txtGeb.Text = ""
                        txtHO.Text = ""

                        If Not IsDBNull(reader("Z_MBR")) Then
                            txtZu.Text = reader("Z_MBR")
                        End If
                        txtSex.Text = ""
                        lblVTag.Text = cGH.GetIndexString(reader("FN_MBR")) & cGH.GetIndexString(reader("VN_MBR")) & DaT
                        btnMBtg.Background = Brushes.LightGreen
                        PType = PersonTyp.MBtg
                    Else
                        MessageBox.Show("Kein Eintrag mit dieser ID gefunden.")
                    End If
                End Using
            End Using
        End Using
    End Sub

    Private Sub btnVBt_Click(sender As Object, e As RoutedEventArgs) Handles btnVBt.Click
        Using conn As New OleDbConnection(connectionString)
            conn.Open()
            ResetAllButtonsBackground(Me)
            DaT = "0000"
            Dim sql As String = pSQL & " WHERE tblVKHID = ?"
            Using cmd As New OleDbCommand(sql, conn)
                cmd.Parameters.AddWithValue("@p1", ID)

                Using reader As OleDbDataReader = cmd.ExecuteReader()
                    If reader.Read() Then
                        If Not IsDBNull(reader("VN_VBT")) Then
                            txtV.Text = reader("VN_VBT")
                        End If
                        If Not IsDBNull(reader("FN_VBT")) Then
                            txtN.Text = reader("FN_VBT")
                        End If

                        If Not IsDBNull(reader("W_EBT")) Then
                            txtWO.Text = reader("W_EBT")
                        End If

                        txtGeb.Text = ""
                        txtHO.Text = ""

                        If Not IsDBNull(reader("Z_VBT")) Then
                            txtZu.Text = reader("Z_VBT")
                        End If
                        txtSex.Text = ""
                        lblVTag.Text = cGH.GetIndexString(reader("FN_VBT")) & cGH.GetIndexString(reader("VN_VBT")) & DaT
                        btnVBt.Background = Brushes.LightGreen
                        PType = PersonTyp.VBt
                    Else
                        MessageBox.Show("Kein Eintrag mit dieser ID gefunden.")
                    End If
                End Using
            End Using
        End Using
    End Sub

    Private Sub btnVBtg_Click(sender As Object, e As RoutedEventArgs) Handles btnVBtg.Click
        Using conn As New OleDbConnection(connectionString)
            conn.Open()
            ResetAllButtonsBackground(Me)
            DaT = "0000"
            Dim sql As String = pSQL & " WHERE tblVKHID = ?"
            Using cmd As New OleDbCommand(sql, conn)
                cmd.Parameters.AddWithValue("@p1", ID)

                Using reader As OleDbDataReader = cmd.ExecuteReader()
                    If reader.Read() Then
                        If Not IsDBNull(reader("VN_VBR")) Then
                            txtV.Text = reader("VN_VBR")
                        End If
                        If Not IsDBNull(reader("FN_VBR")) Then
                            txtN.Text = reader("FN_VBR")
                        End If

                        If Not IsDBNull(reader("W_EBR")) Then
                            txtWO.Text = reader("W_EBR")
                        End If

                        txtGeb.Text = ""
                        txtHO.Text = ""

                        If Not IsDBNull(reader("Z_VBR")) Then
                            txtZu.Text = reader("Z_VBR")
                        End If
                        txtSex.Text = ""
                        lblVTag.Text = cGH.GetIndexString(reader("FN_VBR")) & cGH.GetIndexString(reader("VN_VBR")) & DaT
                        btnVBtg.Background = Brushes.LightGreen
                        PType = PersonTyp.VBtg
                    Else
                        MessageBox.Show("Kein Eintrag mit dieser ID gefunden.")
                    End If
                End Using
            End Using
        End Using
    End Sub

    Private Sub btnZ1_Click(sender As Object, e As RoutedEventArgs) Handles btnZ1.Click
        Using conn As New OleDbConnection(connectionString)
            conn.Open()
            ResetAllButtonsBackground(Me)
            DaT = "0000"
            Dim sql As String = pSQL & " WHERE tblVKHID = ?"
            Using cmd As New OleDbCommand(sql, conn)
                cmd.Parameters.AddWithValue("@p1", ID)

                Using reader As OleDbDataReader = cmd.ExecuteReader()
                    If reader.Read() Then
                        If Not IsDBNull(reader("VN_HZ1")) Then
                            txtV.Text = reader("VN_HZ1")
                        End If
                        If Not IsDBNull(reader("FN_HZ1")) Then
                            txtN.Text = reader("FN_HZ1")
                        End If

                        txtWO.Text = ""

                        txtGeb.Text = ""
                        txtHO.Text = ""

                        If Not IsDBNull(reader("Z_HZ1")) Then
                            txtZu.Text = reader("Z_HZ1")
                        End If
                        If Not IsDBNull(reader("G_HZ1")) Then
                            txtSex.Text = reader("G_HZ1")
                        End If
                        lblVTag.Text = cGH.GetIndexString(reader("FN_HZ1")) & cGH.GetIndexString(reader("VN_HZ1")) & DaT
                        btnZ1.Background = Brushes.LightGreen
                        PType = PersonTyp.Z1
                    Else
                        MessageBox.Show("Kein Eintrag mit dieser ID gefunden.")
                    End If
                End Using
            End Using
        End Using
    End Sub

    Private Sub btnZ2_Click(sender As Object, e As RoutedEventArgs) Handles btnZ2.Click
        Using conn As New OleDbConnection(connectionString)
            conn.Open()
            ResetAllButtonsBackground(Me)
            DaT = "0000"
            Dim sql As String = pSQL & " WHERE tblVKHID = ?"
            Using cmd As New OleDbCommand(sql, conn)
                cmd.Parameters.AddWithValue("@p1", ID)

                Using reader As OleDbDataReader = cmd.ExecuteReader()
                    If reader.Read() Then
                        If Not IsDBNull(reader("VN_HZ2")) Then
                            txtV.Text = reader("VN_HZ2")
                        End If
                        If Not IsDBNull(reader("FN_HZ2")) Then
                            txtN.Text = reader("FN_HZ2")
                        End If

                        txtWO.Text = ""

                        txtGeb.Text = ""
                        txtHO.Text = ""

                        If Not IsDBNull(reader("Z_HZ2")) Then
                            txtZu.Text = reader("Z_HZ2")
                        End If
                        If Not IsDBNull(reader("G_HZ2")) Then
                            txtSex.Text = reader("G_HZ2")
                        End If
                        lblVTag.Text = cGH.GetIndexString(reader("FN_HZ2")) & cGH.GetIndexString(reader("VN_HZ2")) & DaT
                        btnZ2.Background = Brushes.LightGreen
                        PType = PersonTyp.Z2
                    Else
                        MessageBox.Show("Kein Eintrag mit dieser ID gefunden.")
                    End If
                End Using
            End Using
        End Using
    End Sub

    Private Sub btnZ3_Click(sender As Object, e As RoutedEventArgs) Handles btnZ3.Click
        Using conn As New OleDbConnection(connectionString)
            conn.Open()
            ResetAllButtonsBackground(Me)
            DaT = "0000"
            Dim sql As String = pSQL & " WHERE tblVKHID = ?"
            Using cmd As New OleDbCommand(sql, conn)
                cmd.Parameters.AddWithValue("@p1", ID)

                Using reader As OleDbDataReader = cmd.ExecuteReader()
                    If reader.Read() Then
                        If Not IsDBNull(reader("VN_HZ3")) Then
                            txtV.Text = reader("VN_HZ3")
                        End If
                        If Not IsDBNull(reader("FN_HZ3")) Then
                            txtN.Text = reader("FN_HZ3")
                        End If

                        txtWO.Text = ""

                        txtGeb.Text = ""
                        txtHO.Text = ""

                        If Not IsDBNull(reader("Z_HZ3")) Then
                            txtZu.Text = reader("Z_HZ3")
                        End If
                        If Not IsDBNull(reader("G_HZ3")) Then
                            txtSex.Text = reader("G_HZ3")
                        End If
                        lblVTag.Text = cGH.GetIndexString(reader("FN_HZ3")) & cGH.GetIndexString(reader("VN_HZ3")) & DaT
                        btnZ3.Background = Brushes.LightGreen
                        PType = PersonTyp.Z3
                    Else
                        MessageBox.Show("Kein Eintrag mit dieser ID gefunden.")
                    End If
                End Using
            End Using
        End Using
    End Sub

    Private Sub btnZ4_Click(sender As Object, e As RoutedEventArgs) Handles btnZ4.Click
        Using conn As New OleDbConnection(connectionString)
            conn.Open()
            ResetAllButtonsBackground(Me)
            DaT = "0000"
            Dim sql As String = pSQL & " WHERE tblVKHID = ?"
            Using cmd As New OleDbCommand(sql, conn)
                cmd.Parameters.AddWithValue("@p1", ID)

                Using reader As OleDbDataReader = cmd.ExecuteReader()
                    If reader.Read() Then
                        If Not IsDBNull(reader("VN_HZ4")) Then
                            txtV.Text = reader("VN_HZ4")
                        End If
                        If Not IsDBNull(reader("FN_HZ4")) Then
                            txtN.Text = reader("FN_HZ4")
                        End If

                        txtWO.Text = ""

                        txtGeb.Text = ""
                        txtHO.Text = ""

                        If Not IsDBNull(reader("Z_HZ4")) Then
                            txtZu.Text = reader("Z_HZ4")
                        End If
                        If Not IsDBNull(reader("G_HZ4")) Then
                            txtSex.Text = reader("G_HZ4")
                        End If
                        lblVTag.Text = cGH.GetIndexString(reader("FN_HZ4")) & cGH.GetIndexString(reader("VN_HZ4")) & DaT
                        btnZ4.Background = Brushes.LightGreen
                        PType = PersonTyp.Z4
                    Else
                        MessageBox.Show("Kein Eintrag mit dieser ID gefunden.")
                    End If
                End Using
            End Using
        End Using
    End Sub

    Private Sub btnNewPerson_Click(sender As Object, e As RoutedEventArgs) Handles btnNewPerson.Click
        Dim strSex As String = ""

        Select Case PType
            Case PersonTyp.Btg, PersonTyp.VBtg, PersonTyp.VBt
                strSex = "m"
            Case PersonTyp.Bt, PersonTyp.MBtg, PersonTyp.MBtg
                strSex = "w"
            Case PersonTyp.Z1, PersonTyp.Z2, PersonTyp.Z3, PersonTyp.Z4
                strSex = txtSex.Text
            Case PersonTyp.Leer
                Exit Sub
        End Select

        If CurrentIDs.ContainsKey(PType) Then
            Exit Sub
        End If

        Dim args As New PersonenUebergabeEventArgs With {
            .Vorname = txtV.Text,
            .Nachname = txtN.Text,
            .EventDatum = txtGeb.Text,
            .EventArt = "Geburt",
            .Referenz = "H " & txtNr.Text,
            .OnlineRef = txtURL.Text,
            .Ort = txtWO.Text,
            .Sex = strSex
        }

        RaiseEvent PersonenUebergabe(Me, args)
    End Sub


    Public Sub PersonReturn(success As Boolean, Optional PID As Integer = 0)
        RaiseEvent PersonRueckgabe(Me, New PersonRueckgabeEventArgs With {
            .Success = success,
            .PID = PID
        })
    End Sub

    Private Sub OnRueckgabe(sender As Object, e As PersonRueckgabeEventArgs)
        CurrentIDs.Add(PType, e.PID)
    End Sub

    Private Sub VKH_Übernahme_Loaded(sender As Object, e As RoutedEventArgs) Handles Me.Loaded
        AddHandler Me.PersonRueckgabe, AddressOf OnRueckgabe

    End Sub
End Class
