Imports System.Data

Public Class VKH_Personen
    Private cGenDB As New inoGenDLL.ClsGenDB(My.Settings.DBPath)
    Private Sub TxtNachname_TextChanged(sender As Object, e As TextChangedEventArgs) Handles TxtNachname.TextChanged
        ApplyFilter()
    End Sub

    Private Sub FilterPerson_SelectionChanged(sender As Object, e As SelectionChangedEventArgs) Handles FilterPerson.SelectionChanged
        ApplyFilter()
    End Sub

    Private Sub VKH_Personen_Initialized(sender As Object, e As EventArgs) Handles Me.Initialized
        FillFilterPerson()
        ApplyFilter()
    End Sub

    Private Sub ApplyFilter()
        Dim filterText As String = ""
        If FilterPerson.SelectedItem IsNot Nothing Then
            filterText = CStr(CType(FilterPerson.SelectedItem, ComboBoxItem).Content)
        End If

        If filterText = "Alle" Then filterText = ""

        Dim dt As DataTable = cGenDB.VKH_Personen
        If dt IsNot Nothing Then
            Dim dv As DataView = dt.DefaultView
            Dim nachname As String = TxtNachname.Text.Replace("'", "''") ' Escape '

            ' Filter auf Nachname & Kategorie
            dv.RowFilter = $"Nachname LIKE '%{nachname}%'"
            If filterText <> "" Then
                dv.RowFilter &= $" AND Person = '{filterText}'"
            End If

            DataGridPersonen.ItemsSource = dv
            UpdateRowCount()
        End If
    End Sub
    Private Sub UpdateRowCount()
        If DataGridPersonen.ItemsSource IsNot Nothing Then
            RowCountText.Text = $"Zeilen: {DataGridPersonen.Items.Count}"
        Else
            RowCountText.Text = "Zeilen: 0"
        End If
    End Sub

    Private Sub FillFilterPerson()
        ' Zuerst leeren
        FilterPerson.Items.Clear()

        Dim Item As New ComboBoxItem With {
            .Content = "Alle",
            .Tag = ""
        }
        FilterPerson.Items.Add(Item)

        Item = New ComboBoxItem With {
            .Content = "Bräutigam",
            .Tag = "Bräutigam"
        }
        FilterPerson.Items.Add(Item)

        Item = New ComboBoxItem With {
            .Content = "Vater Bräutigam",
            .Tag = "Vater Bräutigam"
        }
        FilterPerson.Items.Add(Item)
        Item = New ComboBoxItem With {
            .Content = "Mutter Bräutigam",
            .Tag = "Mutter Bräutigam"
        }
        FilterPerson.Items.Add(Item)

        Item = New ComboBoxItem With {
            .Content = "Braut",
            .Tag = "Braut"
        }
        FilterPerson.Items.Add(Item)

        Item = New ComboBoxItem With {
            .Content = "Vater Braut",
            .Tag = "Vater Braut"
        }
        FilterPerson.Items.Add(Item)

        Item = New ComboBoxItem With {
            .Content = "Mutter Braut",
            .Tag = "Mutter Braut"
        }
        FilterPerson.Items.Add(Item)



        FilterPerson.SelectedIndex = 0
    End Sub

    Private Sub DataGridPersonen_AutoGeneratedColumns(sender As Object, e As EventArgs) Handles DataGridPersonen.AutoGeneratedColumns
        For Each col In DataGridPersonen.Columns
            If col.Header IsNot Nothing Then
                Select Case col.Header.ToString()

                    Case "HDatum"
                        Dim textCol = TryCast(col, DataGridTextColumn)
                        If textCol IsNot Nothing Then
                            Dim oldBinding = TryCast(textCol.Binding, Binding)
                            If oldBinding IsNot Nothing Then
                                textCol.Binding = New Binding(oldBinding.Path.Path) With {
                                    .StringFormat = "dd.MM.yyyy"
                                }
                            End If
                        End If

                End Select
            End If
        Next

        DataGridPersonen.IsReadOnly = True
        DataGridPersonen.CanUserAddRows = False
        DataGridPersonen.CanUserDeleteRows = False
    End Sub
End Class
