Imports System.Data
Imports System.Data.OleDb
Imports inoGen.MdlPdfAhnentafel
Imports inoGenDLL
Imports iText.StyledXmlParser.Jsoup.[Select].Evaluator

Public Class VKH_Übernahme
    Private connectionString As String =
   String.Format("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=""{0}"";", My.Settings.DBPath)

    Private dt As New DataTable()
    Private dtP As New DataTable()
    Private dtH As New DataTable()

    Private isNewRecord As Boolean = False
    Private ID As Integer? = Nothing
    Private testDate As String

    Private pSQL As String = "SELECT
            *
        FROM
            tblVKH"

    Private cDB As New clsDB(My.Settings.DBPath)
    Private cGDB As New ClsGenDB(My.Settings.DBPath)
    Private cGH As New ClsGenHelper

    Private NT As String = "____"
    Private VT As String = "____"
    Private DaT As String = "0000"

    Public Event PersonenUebergabe As EventHandler(Of PersonenUebergabeEventArgs)
    Public Event PersonenUebergabeEreignis As EventHandler(Of PersonenUebergabeEreignisEventArgs)
    Public Event PersonRueckgabe As EventHandler(Of PersonRueckgabeEventArgs)
    Public Event FamilyUbergabe As EventHandler(Of FamilyUebergabeEventArgs)
    Public Event FamilyRueckgabe As EventHandler(Of PersonRueckgabeEventArgs)

    Public Enum PersonTyp
        Leer
        K
        V
        M
        Btg
        VBtg
        MBtg
        Bt
        VBt
        MBt
        Z1
        Z2
        Z3
        Z4
    End Enum

    Public PType As PersonTyp
    Public FType As PersonTyp

    Dim CurrentIDs As New Dictionary(Of PersonTyp, Integer)
    Dim CurrentFIDs As New Dictionary(Of PersonTyp, Integer)

    Public Sub New()
        InitializeComponent()

        If My.Settings.LastVKHIDÜbergabe > 0 Then
            ID = My.Settings.LastVKHIDÜbergabe
            FillEntry(ID)
        Else
            'btnNew_Click(Nothing, Nothing)
        End If

        LoadData()
        LoadEventListe()

        AddHandler Me.Loaded, AddressOf OnLoaded
    End Sub

    Private Sub OnLoaded(sender As Object, e As RoutedEventArgs)

        'RaiseEvent RequestResizeMainWindow(1300)
    End Sub
    Private Sub dgEintrag_AutoGeneratedColumns(sender As Object, e As EventArgs) Handles dgEintrag.AutoGeneratedColumns
        For Each col In dgEintrag.Columns
            If col.Header IsNot Nothing Then
                Select Case col.Header.ToString()
                    Case "SEITE_H", "NR_H", "VN_BR", "FN_BR", "VN_BT", "FN_BT"
                    Case "HDatum"
                        Dim textCol = TryCast(col, DataGridTextColumn)
                        If textCol IsNot Nothing Then
                            Dim oldBinding = TryCast(textCol.Binding, Binding)
                            If oldBinding IsNot Nothing Then
                                textCol.Binding = New Binding(oldBinding.Path.Path) With {
                                    .StringFormat = "dd.MM.yyyy"
                                }
                            End If
                        End If
                    Case Else
                        col.Visibility = Visibility.Collapsed
                End Select
            End If
        Next

        dgEintrag.IsReadOnly = True
        dgEintrag.CanUserAddRows = False
        dgEintrag.CanUserDeleteRows = False
    End Sub

    Private Sub dgEintrag_MouseDoubleClick(sender As Object, e As MouseButtonEventArgs)
        Dim rowView As DataRowView = CType(dgEintrag.SelectedItem, DataRowView)
        If rowView IsNot Nothing Then
            ID = Convert.ToInt32(rowView("tblVKHID"))
            FillEntry(ID)
            My.Settings.LastVKHIDÜbergabe = ID.Value
            My.Settings.Save()
        End If

    End Sub

    Private Sub LoadData()
        Dim strSQL As String = pSQL & " ORDER BY BUCH_H, SEITE_H, NR_H"


        Try
            Using conn As New OleDbConnection(connectionString)
                conn.Open()
                Dim cmd As New OleDbCommand(strSQL, conn)
                Dim adapter As New OleDbDataAdapter(cmd)
                dt.Clear()
                adapter.Fill(dt)
            End Using

            dgEintrag.ItemsSource = dt.DefaultView

        Catch ex As Exception
            MessageBox.Show("Fehler: " & ex.Message)
        End Try

        If ID.HasValue Then
            For Each rowView As DataRowView In dgEintrag.Items
                If CInt(rowView("tblVKHID")) = ID Then

                    dgEintrag.SelectedItem = rowView

                    dgEintrag.ScrollIntoView(rowView)

                    Exit For
                End If
            Next
        End If

        FillPersons()
        FillMarriage()
    End Sub

    Private Sub FillPersons()
        dtP.Clear()
        dtP = cGDB.GetSearchPersons

        dgPersonDetails.ItemsSource = dtP.DefaultView
    End Sub

    Private Sub FillMarriage()
        dtH.Clear()
        dtH = cGDB.GetFamilies

        dgHeiratDetails.ItemsSource = dtH.DefaultView
    End Sub

    Private Sub FillEntry(EID As Integer)
        Using conn As New OleDbConnection(connectionString)
            isNewRecord = False
            PType = PersonTyp.Leer
            CurrentIDs.Clear()
            CurrentFIDs.Clear()

            ClearAllTextBoxes(Me)
            ResetAllButtonsBackground(Me, True)
            conn.Open()
            Dim sql As String = pSQL & " WHERE tblVKHID = ?"
            Using cmd As New OleDbCommand(sql, conn)
                cmd.Parameters.AddWithValue("@p1", EID)

                Using reader As OleDbDataReader = cmd.ExecuteReader()
                    If reader.Read() Then
                        If Not IsDBNull(reader("BUCH_H")) Then
                            txtQuelle.Text = reader("BUCH_H")
                        End If

                        If Not IsDBNull(reader("SEITE_H")) Then
                            txtSeite.Text = reader("SEITE_H")
                        End If

                        If Not IsDBNull(reader("NR_H")) Then
                            txtNr.Text = reader("NR_H")
                        End If

                        If Not IsDBNull(reader("HDatum")) Then
                            txtHDatum.Text = reader("HDatum")
                            DaT = Year(txtHDatum.Text)
                        End If

                        If Not IsDBNull(reader("DimDatum")) Then
                            txtDimDatum.Text = reader("DimDatum")
                        End If

                        If Not IsDBNull(reader("OnlineReference")) Then
                            txtURL.Text = reader("OnlineReference")
                        End If
                        If Not IsDBNull(reader("ReferenceDetails")) Then
                            txtQuelleSeite.Text = reader("ReferenceDetails")
                        End If

                        ID = EID

                        If Not IsDBNull(reader("VN_BR")) Then
                            btnBtg.IsEnabled = IIf(reader("VN_BR") <> "", True, False)
                            btnNewHEintrag.IsEnabled = IIf(reader("VN_BR") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("FN_BR")) And btnBtg.IsEnabled = False Then
                            btnBtg.IsEnabled = IIf(reader("FN_BR") <> "", True, False)
                            btnNewHEintrag.IsEnabled = IIf(reader("FN_BR") <> "", True, False)
                        End If
                        'If Not IsDBNull(reader("GebDatum_BR")) Then
                        '    '   btnBtg.IsEnabled = IIf(reader("GebDatum_BR") <> "", True, False)
                        'End If
                        If Not IsDBNull(reader("W_BR")) And btnBtg.IsEnabled = False Then
                            btnBtg.IsEnabled = IIf(reader("W_BR") <> "", True, False)
                            btnNewHEintrag.IsEnabled = IIf(reader("W_BR") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("H_BR")) And btnBtg.IsEnabled = False Then
                            btnBtg.IsEnabled = IIf(reader("H_BR") <> "", True, False)
                            btnNewHEintrag.IsEnabled = IIf(reader("H_BR") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("Z_BR")) And btnBtg.IsEnabled = False Then
                            btnBtg.IsEnabled = IIf(reader("Z_BR") <> "", True, False)
                            btnNewHEintrag.IsEnabled = IIf(reader("Z_BR") <> "", True, False)
                        End If

                        If Not IsDBNull(reader("VN_VBR")) Then
                            btnVBtg.IsEnabled = IIf(reader("VN_VBR") <> "", True, False)
                            btnNewHVEintrag.IsEnabled = IIf(reader("VN_VBR") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("FN_VBR")) And btnVBtg.IsEnabled = False Then
                            btnVBtg.IsEnabled = IIf(reader("FN_VBR") <> "", True, False)
                            btnNewHVEintrag.IsEnabled = IIf(reader("FN_VBR") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("Z_VBR")) And btnVBtg.IsEnabled = False Then
                            btnVBtg.IsEnabled = IIf(reader("Z_VBR") <> "", True, False)
                            btnNewHVEintrag.IsEnabled = IIf(reader("Z_VBR") <> "", True, False)
                        End If

                        If Not IsDBNull(reader("VN_MBR")) Then
                            btnMBtg.IsEnabled = IIf(reader("VN_MBR") <> "", True, False)
                            If btnNewHVEintrag.IsEnabled = False Then
                                btnNewHVEintrag.IsEnabled = IIf(reader("VN_MBR") <> "", True, False)
                            End If
                        End If
                            If Not IsDBNull(reader("FN_MBR")) And btnMBtg.IsEnabled = False Then
                            btnMBtg.IsEnabled = IIf(reader("FN_MBR") <> "", True, False)
                            If btnNewHVEintrag.IsEnabled = False Then
                                btnNewHVEintrag.IsEnabled = IIf(reader("VN_MBR") <> "", True, False)
                            End If
                        End If
                        If Not IsDBNull(reader("Z_MBR")) And btnMBtg.IsEnabled = False Then
                            btnMBtg.IsEnabled = IIf(reader("Z_MBR") <> "", True, False)
                            If btnNewHVEintrag.IsEnabled = False Then
                                btnNewHVEintrag.IsEnabled = IIf(reader("VN_MBR") <> "", True, False)
                            End If
                        End If
                        'If Not IsDBNull(reader("W_EBR")) Then
                        '    btnVBtg.IsEnabled = True
                        'End If

                        If Not IsDBNull(reader("VN_BT")) Then
                            btnBt.IsEnabled = IIf(reader("VN_BT") <> "", True, False)
                            btnNewHEintrag.IsEnabled = IIf(reader("VN_BT") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("FN_BT")) And btnBt.IsEnabled = False Then
                            btnBt.IsEnabled = IIf(reader("FN_BT") <> "", True, False)
                            btnNewHEintrag.IsEnabled = IIf(reader("FN_BT") <> "", True, False)
                        End If
                        'If Not IsDBNull(reader("GebDatum_BT")) Then
                        '    btnBt.IsEnabled = True
                        'End If
                        If Not IsDBNull(reader("W_BT")) And btnBt.IsEnabled = False Then
                            btnBt.IsEnabled = IIf(reader("W_BT") <> "", True, False)
                            btnNewHEintrag.IsEnabled = IIf(reader("W_BT") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("H_BT")) And btnBt.IsEnabled = False Then
                            btnBt.IsEnabled = IIf(reader("H_BT") <> "", True, False)
                            btnNewHEintrag.IsEnabled = IIf(reader("H_BT") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("Z_BT")) And btnBt.IsEnabled = False Then
                            btnBt.IsEnabled = IIf(reader("Z_BT") <> "", True, False)
                            btnNewHEintrag.IsEnabled = IIf(reader("Z_BT") <> "", True, False)
                        End If

                        If Not IsDBNull(reader("VN_VBT")) Then
                            btnVBt.IsEnabled = IIf(reader("VN_VBT") <> "", True, False)
                            If btnNewHMEintrag.IsEnabled = False Then
                                btnNewHMEintrag.IsEnabled = IIf(reader("VN_VBT") <> "", True, False)
                            End If
                        End If
                        If Not IsDBNull(reader("FN_VBT")) And btnVBt.IsEnabled = False Then
                            btnVBt.IsEnabled = IIf(reader("FN_VBT") <> "", True, False)
                            If btnNewHMEintrag.IsEnabled = False Then
                                btnNewHMEintrag.IsEnabled = IIf(reader("VN_VBT") <> "", True, False)
                            End If
                        End If
                        If Not IsDBNull(reader("Z_VBT")) And btnVBt.IsEnabled = False Then
                            btnVBt.IsEnabled = IIf(reader("Z_VBT") <> "", True, False)
                            If btnNewHMEintrag.IsEnabled = False Then
                                btnNewHMEintrag.IsEnabled = IIf(reader("VN_VBT") <> "", True, False)
                            End If
                        End If

                        If Not IsDBNull(reader("VN_MBT")) Then
                            btnMBt.IsEnabled = IIf(reader("VN_MBT") <> "", True, False)
                            If btnNewHMEintrag.IsEnabled = False Then
                                btnNewHMEintrag.IsEnabled = IIf(reader("VN_VBT") <> "", True, False)
                            End If
                        End If
                        If Not IsDBNull(reader("FN_MBT")) And btnMBt.IsEnabled = False Then
                            btnMBt.IsEnabled = IIf(reader("FN_MBT") <> "", True, False)
                            If btnNewHMEintrag.IsEnabled = False Then
                                btnNewHMEintrag.IsEnabled = IIf(reader("VN_VBT") <> "", True, False)
                            End If
                        End If
                        If Not IsDBNull(reader("Z_MBT")) And btnMBt.IsEnabled = False Then
                            btnMBt.IsEnabled = IIf(reader("Z_MBT") <> "", True, False)
                            If btnNewHMEintrag.IsEnabled = False Then
                                btnNewHMEintrag.IsEnabled = IIf(reader("VN_VBT") <> "", True, False)
                            End If
                        End If
                        'If Not IsDBNull(reader("W_EBT")) Then
                        '    txtWEBt.Text = reader("W_EBT")
                        'End If

                        If Not IsDBNull(reader("ANM_H")) Then
                            txtInfo.Text = reader("ANM_H")
                        End If

                        If Not IsDBNull(reader("VN_HZ1")) Then
                            btnZ1.IsEnabled = IIf(reader("VN_HZ1") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("FN_HZ1")) And btnZ1.IsEnabled = False Then
                            btnZ1.IsEnabled = IIf(reader("FN_HZ1") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("G_HZ1")) And btnZ1.IsEnabled = False Then
                            btnZ1.IsEnabled = IIf(reader("G_HZ1") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("Z_HZ1")) And btnZ1.IsEnabled = False Then
                            btnZ1.IsEnabled = IIf(reader("Z_HZ1") <> "", True, False)
                        End If

                        If Not IsDBNull(reader("VN_HZ2")) Then
                            btnZ2.IsEnabled = IIf(reader("VN_HZ2") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("FN_HZ2")) And btnZ2.IsEnabled = False Then
                            btnZ2.IsEnabled = IIf(reader("FN_HZ2") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("G_HZ2")) And btnZ2.IsEnabled = False Then
                            btnZ2.IsEnabled = IIf(reader("G_HZ2") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("Z_HZ2")) And btnZ2.IsEnabled = False Then
                            btnZ2.IsEnabled = IIf(reader("Z_HZ2") <> "", True, False)
                        End If

                        If Not IsDBNull(reader("VN_HZ3")) Then
                            btnZ3.IsEnabled = IIf(reader("VN_HZ3") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("FN_HZ3")) And btnZ3.IsEnabled = False Then
                            btnZ3.IsEnabled = IIf(reader("FN_HZ3") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("G_HZ3")) And btnZ3.IsEnabled = False Then
                            btnZ3.IsEnabled = IIf(reader("G_HZ3") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("Z_HZ3")) And btnZ3.IsEnabled = False Then
                            btnZ3.IsEnabled = IIf(reader("Z_HZ3") <> "", True, False)
                        End If

                        If Not IsDBNull(reader("VN_HZ4")) Then
                            btnZ4.IsEnabled = IIf(reader("VN_HZ4") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("FN_HZ4")) And btnZ4.IsEnabled = False Then
                            btnZ4.IsEnabled = IIf(reader("FN_HZ4") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("G_HZ4")) And btnZ4.IsEnabled = False Then
                            btnZ4.IsEnabled = IIf(reader("G_HZ4") <> "", True, False)
                        End If
                        If Not IsDBNull(reader("Z_HZ4")) And btnZ4.IsEnabled = False Then
                            btnZ4.IsEnabled = IIf(reader("Z_HZ4") <> "", True, False)
                        End If

                        txtIndexH.Text = cGH.GetIndexString(reader("FN_BR")) & cGH.GetIndexString(reader("FN_BT")) & DaT
                        DaT = "0000"
                        txtIndexBtg.Text = cGH.GetIndexString(reader("FN_VBR")) & cGH.GetIndexString(reader("FN_MBR")) & DaT
                        txtIndexBt.Text = cGH.GetIndexString(reader("FN_VBT")) & cGH.GetIndexString(reader("FN_MBT")) & DaT
                    Else
                        MessageBox.Show("Kein Eintrag mit dieser ID gefunden.")
                    End If
                End Using
            End Using
        End Using

    End Sub

    Public Sub ClearAllTextBoxes(parent As DependencyObject)
        For i As Integer = 0 To VisualTreeHelper.GetChildrenCount(parent) - 1
            Dim child As DependencyObject = VisualTreeHelper.GetChild(parent, i)

            If TypeOf child Is TextBox Then
                DirectCast(child, TextBox).Clear()
            Else
                ClearAllTextBoxes(child)
            End If
        Next

    End Sub

    Private Sub btnBt_Click(sender As Object, e As RoutedEventArgs) Handles btnBt.Click
        Using conn As New OleDbConnection(connectionString)
            conn.Open()
            ResetAllButtonsBackground(Me)
            DaT = "0000"
            Dim sql As String = pSQL & " WHERE tblVKHID = ?"
            Using cmd As New OleDbCommand(sql, conn)
                cmd.Parameters.AddWithValue("@p1", ID)

                Using reader As OleDbDataReader = cmd.ExecuteReader()
                    If reader.Read() Then
                        If Not IsDBNull(reader("VN_BT")) Then
                            txtV.Text = reader("VN_BT")
                        End If

                        If Not IsDBNull(reader("FN_BT")) Then
                            txtN.Text = reader("FN_BT")
                        End If
                        If Not IsDBNull(reader("GebDatum_BT")) Then
                            txtGeb.Text = reader("GebDatum_BT")
                            DaT = Year(txtGeb.Text)
                        End If
                        If Not IsDBNull(reader("W_BT")) Then
                            txtWO.Text = reader("W_BT")
                        End If
                        If Not IsDBNull(reader("H_BT")) Then
                            txtHO.Text = reader("H_BT")
                        End If
                        If Not IsDBNull(reader("Z_BT")) Then
                            txtZu.Text = reader("Z_BT")
                        End If
                        txtSex.Text = ""
                        lblVTag.Text = cGH.GetIndexString(reader("FN_BT")) & cGH.GetIndexString(reader("VN_BT")) & DaT
                        btnBt.Background = Brushes.LightGreen
                        PType = PersonTyp.Bt
                        PFilterSetzen()
                    Else
                        MessageBox.Show("Kein Eintrag mit dieser ID gefunden.")
                    End If
                End Using
            End Using
        End Using
    End Sub

    Private Sub btnBtg_Click(sender As Object, e As RoutedEventArgs) Handles btnBtg.Click
        Using conn As New OleDbConnection(connectionString)
            conn.Open()
            ResetAllButtonsBackground(Me)
            DaT = "0000"
            Dim sql As String = pSQL & " WHERE tblVKHID = ?"
            Using cmd As New OleDbCommand(sql, conn)
                cmd.Parameters.AddWithValue("@p1", ID)

                Using reader As OleDbDataReader = cmd.ExecuteReader()
                    If reader.Read() Then
                        If Not IsDBNull(reader("VN_BR")) Then
                            txtV.Text = reader("VN_BR")
                        End If

                        If Not IsDBNull(reader("FN_BR")) Then
                            txtN.Text = reader("FN_BR")
                        End If
                        If Not IsDBNull(reader("GebDatum_BR")) Then
                            txtGeb.Text = reader("GebDatum_BR")
                            DaT = Year(txtGeb.Text)
                        End If
                        If Not IsDBNull(reader("W_BR")) Then
                            txtWO.Text = reader("W_BR")
                        End If
                        If Not IsDBNull(reader("H_BR")) Then
                            txtHO.Text = reader("H_BR")
                        End If
                        If Not IsDBNull(reader("Z_BR")) Then
                            txtZu.Text = reader("Z_BR")
                        End If
                        txtSex.Text = ""
                        lblVTag.Text = cGH.GetIndexString(reader("FN_BR")) & cGH.GetIndexString(reader("VN_BR")) & DaT
                        btnBtg.Background = Brushes.LightGreen
                        PType = PersonTyp.Btg
                        PFilterSetzen()
                    Else
                        MessageBox.Show("Kein Eintrag mit dieser ID gefunden.")
                    End If
                End Using
            End Using
        End Using
    End Sub

    Private Sub ResetAllButtonsBackground(root As DependencyObject, Optional blnAll As Boolean = False)

        For i As Integer = 0 To VisualTreeHelper.GetChildrenCount(root) - 1
            Dim child = VisualTreeHelper.GetChild(root, i)

            If TypeOf child Is Button Then
                Dim btn = DirectCast(child, Button)
                btn.ClearValue(Button.BackgroundProperty)
                btn.ClearValue(Button.BorderThicknessProperty)
                If blnAll Then
                    btn.IsEnabled = False
                End If

                If btn.Name.Length > 4 Then
                    Dim enumName As String = btn.Name.Substring(3)
                    Dim pType As PersonTyp
                    Dim pid As Integer

                    If [Enum].TryParse(enumName, True, pType) Then

                        If CurrentIDs.TryGetValue(pType, pid) Then
                            'MessageBox.Show($"ID gefunden: {pid} Typ {btn.Name} ")
                            btn.BorderThickness = New Thickness(3)
                        Else
                            ' MessageBox.Show($"Keine ID für {pType} vorhanden")
                        End If

                    Else
                        Select Case btn.Name
                            Case "btnNewHEintrag"
                                If CurrentFIDs.TryGetValue(PersonTyp.Btg, pid) Then
                                    'MessageBox.Show($"ID gefunden: {pid} Typ {btn.Name} ")
                                    btn.BorderThickness = New Thickness(3)
                                Else
                                    ' MessageBox.Show($"Keine ID für {pType} vorhanden")
                                End If
                            Case "btnNewHMEintrag"
                                If CurrentFIDs.TryGetValue(PersonTyp.MBtg, pid) Then
                                    'MessageBox.Show($"ID gefunden: {pid} Typ {btn.Name} ")
                                    btn.BorderThickness = New Thickness(3)
                                Else
                                    ' MessageBox.Show($"Keine ID für {pType} vorhanden")
                                End If
                            Case "btnNewHVEintrag"
                                If CurrentFIDs.TryGetValue(PersonTyp.VBtg, pid) Then
                                    'MessageBox.Show($"ID gefunden: {pid} Typ {btn.Name} ")
                                    btn.BorderThickness = New Thickness(3)
                                Else
                                    ' MessageBox.Show($"Keine ID für {pType} vorhanden")
                                End If
                        End Select

                    End If
                End If
            End If

            ResetAllButtonsBackground(child)
        Next

    End Sub

    Private Sub btnMBt_Click(sender As Object, e As RoutedEventArgs) Handles btnMBt.Click
        Using conn As New OleDbConnection(connectionString)
            conn.Open()
            ResetAllButtonsBackground(Me)
            DaT = "0000"
            Dim sql As String = pSQL & " WHERE tblVKHID = ?"
            Using cmd As New OleDbCommand(sql, conn)
                cmd.Parameters.AddWithValue("@p1", ID)

                Using reader As OleDbDataReader = cmd.ExecuteReader()
                    If reader.Read() Then
                        If Not IsDBNull(reader("VN_MBT")) Then
                            txtV.Text = reader("VN_MBT")
                        End If
                        If Not IsDBNull(reader("FN_MBT")) Then
                            txtN.Text = reader("FN_MBT")
                        End If

                        If Not IsDBNull(reader("W_EBT")) Then
                            txtWO.Text = reader("W_EBT")
                        End If

                        txtGeb.Text = ""
                        txtHO.Text = ""

                        If Not IsDBNull(reader("Z_MBT")) Then
                            txtZu.Text = reader("Z_MBT")
                        End If
                        txtSex.Text = ""
                        lblVTag.Text = cGH.GetIndexString(reader("FN_MBT")) & cGH.GetIndexString(reader("VN_MBT")) & DaT
                        btnMBt.Background = Brushes.LightGreen
                        PType = PersonTyp.MBt
                        PFilterSetzen()
                    Else
                        MessageBox.Show("Kein Eintrag mit dieser ID gefunden.")
                    End If
                End Using
            End Using
        End Using
    End Sub

    Private Sub btnMBtg_Click(sender As Object, e As RoutedEventArgs) Handles btnMBtg.Click
        Using conn As New OleDbConnection(connectionString)
            conn.Open()
            ResetAllButtonsBackground(Me)
            DaT = "0000"
            Dim sql As String = pSQL & " WHERE tblVKHID = ?"
            Using cmd As New OleDbCommand(sql, conn)
                cmd.Parameters.AddWithValue("@p1", ID)

                Using reader As OleDbDataReader = cmd.ExecuteReader()
                    If reader.Read() Then
                        If Not IsDBNull(reader("VN_MBR")) Then
                            txtV.Text = reader("VN_MBR")
                        End If
                        If Not IsDBNull(reader("FN_MBR")) Then
                            txtN.Text = reader("FN_MBR")
                        End If

                        If Not IsDBNull(reader("W_EBR")) Then
                            txtWO.Text = reader("W_EBR")
                        End If

                        txtGeb.Text = ""
                        txtHO.Text = ""

                        If Not IsDBNull(reader("Z_MBR")) Then
                            txtZu.Text = reader("Z_MBR")
                        End If
                        txtSex.Text = ""
                        lblVTag.Text = cGH.GetIndexString(reader("FN_MBR")) & cGH.GetIndexString(reader("VN_MBR")) & DaT
                        btnMBtg.Background = Brushes.LightGreen
                        PType = PersonTyp.MBtg
                        PFilterSetzen()
                    Else
                        MessageBox.Show("Kein Eintrag mit dieser ID gefunden.")
                    End If
                End Using
            End Using
        End Using
    End Sub

    Private Sub btnVBt_Click(sender As Object, e As RoutedEventArgs) Handles btnVBt.Click
        Using conn As New OleDbConnection(connectionString)
            conn.Open()
            ResetAllButtonsBackground(Me)
            DaT = "0000"
            Dim sql As String = pSQL & " WHERE tblVKHID = ?"
            Using cmd As New OleDbCommand(sql, conn)
                cmd.Parameters.AddWithValue("@p1", ID)

                Using reader As OleDbDataReader = cmd.ExecuteReader()
                    If reader.Read() Then
                        If Not IsDBNull(reader("VN_VBT")) Then
                            txtV.Text = reader("VN_VBT")
                        End If
                        If Not IsDBNull(reader("FN_VBT")) Then
                            txtN.Text = reader("FN_VBT")
                        End If

                        If Not IsDBNull(reader("W_EBT")) Then
                            txtWO.Text = reader("W_EBT")
                        End If

                        txtGeb.Text = ""
                        txtHO.Text = ""

                        If Not IsDBNull(reader("Z_VBT")) Then
                            txtZu.Text = reader("Z_VBT")
                        End If
                        txtSex.Text = ""
                        lblVTag.Text = cGH.GetIndexString(reader("FN_VBT")) & cGH.GetIndexString(reader("VN_VBT")) & DaT
                        btnVBt.Background = Brushes.LightGreen
                        PType = PersonTyp.VBt
                        PFilterSetzen()
                    Else
                        MessageBox.Show("Kein Eintrag mit dieser ID gefunden.")
                    End If
                End Using
            End Using
        End Using
    End Sub

    Private Sub btnVBtg_Click(sender As Object, e As RoutedEventArgs) Handles btnVBtg.Click
        Using conn As New OleDbConnection(connectionString)
            conn.Open()
            ResetAllButtonsBackground(Me)
            DaT = "0000"
            Dim sql As String = pSQL & " WHERE tblVKHID = ?"
            Using cmd As New OleDbCommand(sql, conn)
                cmd.Parameters.AddWithValue("@p1", ID)

                Using reader As OleDbDataReader = cmd.ExecuteReader()
                    If reader.Read() Then
                        If Not IsDBNull(reader("VN_VBR")) Then
                            txtV.Text = reader("VN_VBR")
                        End If
                        If Not IsDBNull(reader("FN_VBR")) Then
                            txtN.Text = reader("FN_VBR")
                        End If

                        If Not IsDBNull(reader("W_EBR")) Then
                            txtWO.Text = reader("W_EBR")
                        End If

                        txtGeb.Text = ""
                        txtHO.Text = ""

                        If Not IsDBNull(reader("Z_VBR")) Then
                            txtZu.Text = reader("Z_VBR")
                        End If
                        txtSex.Text = ""
                        lblVTag.Text = cGH.GetIndexString(reader("FN_VBR")) & cGH.GetIndexString(reader("VN_VBR")) & DaT
                        btnVBtg.Background = Brushes.LightGreen
                        PType = PersonTyp.VBtg
                        PFilterSetzen()
                    Else
                        MessageBox.Show("Kein Eintrag mit dieser ID gefunden.")
                    End If
                End Using
            End Using
        End Using
    End Sub

    Private Sub btnZ1_Click(sender As Object, e As RoutedEventArgs) Handles btnZ1.Click
        Using conn As New OleDbConnection(connectionString)
            conn.Open()
            ResetAllButtonsBackground(Me)
            DaT = "0000"
            Dim sql As String = pSQL & " WHERE tblVKHID = ?"
            Using cmd As New OleDbCommand(sql, conn)
                cmd.Parameters.AddWithValue("@p1", ID)

                Using reader As OleDbDataReader = cmd.ExecuteReader()
                    If reader.Read() Then
                        If Not IsDBNull(reader("VN_HZ1")) Then
                            txtV.Text = reader("VN_HZ1")
                        End If
                        If Not IsDBNull(reader("FN_HZ1")) Then
                            txtN.Text = reader("FN_HZ1")
                        End If

                        txtWO.Text = ""

                        txtGeb.Text = ""
                        txtHO.Text = ""

                        If Not IsDBNull(reader("Z_HZ1")) Then
                            txtZu.Text = reader("Z_HZ1")
                        End If
                        If Not IsDBNull(reader("G_HZ1")) Then
                            txtSex.Text = reader("G_HZ1")
                        End If
                        lblVTag.Text = cGH.GetIndexString(reader("FN_HZ1")) & cGH.GetIndexString(reader("VN_HZ1")) & DaT
                        btnZ1.Background = Brushes.LightGreen
                        PType = PersonTyp.Z1
                        PFilterSetzen()
                    Else
                        MessageBox.Show("Kein Eintrag mit dieser ID gefunden.")
                    End If
                End Using
            End Using
        End Using
    End Sub

    Private Sub btnZ2_Click(sender As Object, e As RoutedEventArgs) Handles btnZ2.Click
        Using conn As New OleDbConnection(connectionString)
            conn.Open()
            ResetAllButtonsBackground(Me)
            DaT = "0000"
            Dim sql As String = pSQL & " WHERE tblVKHID = ?"
            Using cmd As New OleDbCommand(sql, conn)
                cmd.Parameters.AddWithValue("@p1", ID)

                Using reader As OleDbDataReader = cmd.ExecuteReader()
                    If reader.Read() Then
                        If Not IsDBNull(reader("VN_HZ2")) Then
                            txtV.Text = reader("VN_HZ2")
                        End If
                        If Not IsDBNull(reader("FN_HZ2")) Then
                            txtN.Text = reader("FN_HZ2")
                        End If

                        txtWO.Text = ""

                        txtGeb.Text = ""
                        txtHO.Text = ""

                        If Not IsDBNull(reader("Z_HZ2")) Then
                            txtZu.Text = reader("Z_HZ2")
                        End If
                        If Not IsDBNull(reader("G_HZ2")) Then
                            txtSex.Text = reader("G_HZ2")
                        End If
                        lblVTag.Text = cGH.GetIndexString(reader("FN_HZ2")) & cGH.GetIndexString(reader("VN_HZ2")) & DaT
                        btnZ2.Background = Brushes.LightGreen
                        PType = PersonTyp.Z2
                        PFilterSetzen()
                    Else
                        MessageBox.Show("Kein Eintrag mit dieser ID gefunden.")
                    End If
                End Using
            End Using
        End Using
    End Sub

    Private Sub btnZ3_Click(sender As Object, e As RoutedEventArgs) Handles btnZ3.Click
        Using conn As New OleDbConnection(connectionString)
            conn.Open()
            ResetAllButtonsBackground(Me)
            DaT = "0000"
            Dim sql As String = pSQL & " WHERE tblVKHID = ?"
            Using cmd As New OleDbCommand(sql, conn)
                cmd.Parameters.AddWithValue("@p1", ID)

                Using reader As OleDbDataReader = cmd.ExecuteReader()
                    If reader.Read() Then
                        If Not IsDBNull(reader("VN_HZ3")) Then
                            txtV.Text = reader("VN_HZ3")
                        End If
                        If Not IsDBNull(reader("FN_HZ3")) Then
                            txtN.Text = reader("FN_HZ3")
                        End If

                        txtWO.Text = ""

                        txtGeb.Text = ""
                        txtHO.Text = ""

                        If Not IsDBNull(reader("Z_HZ3")) Then
                            txtZu.Text = reader("Z_HZ3")
                        End If
                        If Not IsDBNull(reader("G_HZ3")) Then
                            txtSex.Text = reader("G_HZ3")
                        End If
                        lblVTag.Text = cGH.GetIndexString(reader("FN_HZ3")) & cGH.GetIndexString(reader("VN_HZ3")) & DaT
                        btnZ3.Background = Brushes.LightGreen
                        PType = PersonTyp.Z3
                        PFilterSetzen()
                    Else
                        MessageBox.Show("Kein Eintrag mit dieser ID gefunden.")
                    End If
                End Using
            End Using
        End Using
    End Sub

    Private Sub btnZ4_Click(sender As Object, e As RoutedEventArgs) Handles btnZ4.Click
        Using conn As New OleDbConnection(connectionString)
            conn.Open()
            ResetAllButtonsBackground(Me)
            DaT = "0000"
            Dim sql As String = pSQL & " WHERE tblVKHID = ?"
            Using cmd As New OleDbCommand(sql, conn)
                cmd.Parameters.AddWithValue("@p1", ID)

                Using reader As OleDbDataReader = cmd.ExecuteReader()
                    If reader.Read() Then
                        If Not IsDBNull(reader("VN_HZ4")) Then
                            txtV.Text = reader("VN_HZ4")
                        End If
                        If Not IsDBNull(reader("FN_HZ4")) Then
                            txtN.Text = reader("FN_HZ4")
                        End If

                        txtWO.Text = ""

                        txtGeb.Text = ""
                        txtHO.Text = ""

                        If Not IsDBNull(reader("Z_HZ4")) Then
                            txtZu.Text = reader("Z_HZ4")
                        End If
                        If Not IsDBNull(reader("G_HZ4")) Then
                            txtSex.Text = reader("G_HZ4")
                        End If
                        lblVTag.Text = cGH.GetIndexString(reader("FN_HZ4")) & cGH.GetIndexString(reader("VN_HZ4")) & DaT
                        btnZ4.Background = Brushes.LightGreen
                        PType = PersonTyp.Z4
                        PFilterSetzen()
                    Else
                        MessageBox.Show("Kein Eintrag mit dieser ID gefunden.")
                    End If
                End Using
            End Using
        End Using
    End Sub

    Private Sub btnNewPerson_Click(sender As Object, e As RoutedEventArgs) Handles btnNewPerson.Click
        Dim strSex As String = ""

        Select Case PType
            Case PersonTyp.Btg, PersonTyp.VBtg, PersonTyp.VBt
                strSex = "m"
            Case PersonTyp.Bt, PersonTyp.MBtg, PersonTyp.MBtg
                strSex = "w"
            Case PersonTyp.Z1, PersonTyp.Z2, PersonTyp.Z3, PersonTyp.Z4
                strSex = txtSex.Text
            Case PersonTyp.Leer
                Exit Sub
        End Select

        If CurrentIDs.ContainsKey(PType) Then
            Exit Sub
        End If

        Dim args As New PersonenUebergabeEventArgs With {
            .Vorname = txtV.Text,
            .Nachname = txtN.Text,
            .EventDatum = txtGeb.Text,
            .EventArt = "Geburt",
            .Referenz = "H " & txtNr.Text,
            .OnlineRef = txtURL.Text,
            .Ort = txtWO.Text,
            .Sex = strSex
        }

        RaiseEvent PersonenUebergabe(Me, args)
    End Sub


    Public Sub PersonReturn(success As Boolean, Optional PID As Integer = 0)
        RaiseEvent PersonRueckgabe(Me, New PersonRueckgabeEventArgs With {
            .Success = success,
            .PID = PID
        })
    End Sub
    Public Sub FamilyReturn(success As Boolean, Optional PID As Integer = 0)
        RaiseEvent FamilyRueckgabe(Me, New PersonRueckgabeEventArgs With {
            .Success = success,
            .PID = PID
        })
    End Sub

    Private Sub OnRueckgabeP(sender As Object, e As PersonRueckgabeEventArgs)
        CurrentIDs.Add(PType, e.PID)
        FillPersons()
        PFilterSetzen()
    End Sub

    Private Sub OnRueckgabeF(sender As Object, e As PersonRueckgabeEventArgs)
        CurrentFIDs.Add(FType, e.PID)
        FillMarriage()
        ' HFilterSetzen("")
    End Sub
    Private Sub VKH_Übernahme_Loaded(sender As Object, e As RoutedEventArgs) Handles Me.Loaded
        AddHandler Me.PersonRueckgabe, AddressOf OnRueckgabeP
        AddHandler Me.FamilyRueckgabe, AddressOf OnRueckgabeF

    End Sub

    Private Sub dgPersonDetails_AutoGeneratedColumns(sender As Object, e As EventArgs) Handles dgPersonDetails.AutoGeneratedColumns
        For Each col In dgPersonDetails.Columns
            If col.Header IsNot Nothing Then
                Select Case col.Header.ToString()
                    Case "tblPersonID", "Datum"
                        col.Visibility = Visibility.Collapsed
                End Select
            End If
        Next

        dgPersonDetails.IsReadOnly = True
        dgPersonDetails.CanUserAddRows = False
        dgPersonDetails.CanUserDeleteRows = False
    End Sub

    Private Sub dgPersonDetails_MouseDoubleClick(sender As Object, e As MouseButtonEventArgs)
        Dim rowView As DataRowView = CType(dgPersonDetails.SelectedItem, DataRowView)
        If rowView IsNot Nothing Then
            Dim id As Integer = Convert.ToInt32(rowView("tblPersonID"))
            CurrentIDs(PType) = id
        End If
    End Sub

    Private Sub PFilterSetzen()
        Dim filter As String = vbNullString
        Dim sep As String = vbNullString
        Dim Sex As String = vbNullString
        If txtN.Text.Trim() <> vbNullString Then
            filter = String.Format("PS LIKE '{0}%'", lblVTag.Text.Trim().Substring(0, 4))
            sep = " AND "
        End If

        Select Case PType
            Case PersonTyp.Btg, PersonTyp.VBtg, PersonTyp.VBt
                Sex = "m"
            Case PersonTyp.Bt, PersonTyp.MBtg, PersonTyp.MBtg
                Sex = "w"
            Case PersonTyp.Z1, PersonTyp.Z2, PersonTyp.Z3, PersonTyp.Z4
                Sex = txtSex.Text
            Case PersonTyp.Leer
                Sex = ""
        End Select

        If Sex <> "" Then
            filter &= sep & String.Format(" Sex = '{0}'", Sex)
            sep = " AND "
        End If

        If Not String.IsNullOrEmpty(filter) Then
            Dim dv As New DataView(dtP)
            dv.RowFilter = filter
            dgPersonDetails.ItemsSource = dv
        Else
            dgPersonDetails.ItemsSource = dtP.DefaultView
        End If


        For Each rowView As DataRowView In dgPersonDetails.Items
            If rowView("PS") = lblVTag.Text.Trim() Then
                dgPersonDetails.SelectedItem = rowView
                dgPersonDetails.ScrollIntoView(rowView)

                Exit For
            End If
        Next

        txtDatum.Text = txtHDatum.Text
    End Sub

    Private Sub LoadEventListe()
        Try
            Dim dtE As New DataTable()
            Using conn As New OleDbConnection(connectionString)
                conn.Open()
                Dim cmd As New OleDbCommand("SELECT tblEreignisArtID, EreignisArt FROM tblEreignisArt WHERE PersonenEreignis = ? ORDER BY Reihenfolge", conn)
                cmd.Parameters.Add("PersonenEreignis", OleDbType.Boolean).Value = True
                Dim adapter As New OleDbDataAdapter(cmd)
                adapter.Fill(dtE)
            End Using

            cbEreignis.ItemsSource = dtE.DefaultView

        Catch ex As Exception
            MessageBox.Show("Fehler beim Laden der Kreise: " & ex.Message)
        End Try
    End Sub

    Private Sub cbEreignis_SelectionChanged(sender As Object, e As SelectionChangedEventArgs) Handles cbEreignis.SelectionChanged
        If cbEreignis.SelectedValue IsNot Nothing Then
            Dim selectedID As Integer = CInt(cbEreignis.SelectedValue)
        End If
        txtEintragZusatz.Text = ""

        Dim row As DataRowView = TryCast(cbEreignis.SelectedItem, DataRowView)
        If row IsNot Nothing Then
            Dim text = row("EreignisArt").ToString()
            If text = "Sterbe" Then
                txtDatum.Text = "< " & txtHDatum.Text
            End If
        End If
    End Sub

    Private Sub btnNewPEintrag_Click(sender As Object, e As RoutedEventArgs) Handles btnNewPEintrag.Click
        Dim pid As Integer
        If CurrentIDs.TryGetValue(PType, pid) Then
            'MessageBox.Show($"ID gefunden: {pid} Typ {btn.Name} ")
        Else
            Exit Sub
        End If

        Dim args As New PersonenUebergabeEreignisEventArgs With {
            .PID = pid,
            .EventDatum = txtDatum.Text,
            .EventArt = cbEreignis.Text,
            .Referenz = "H " & txtNr.Text,
            .OnlineRef = txtURL.Text,
            .Ort = txtWO.Text,
            .Zusatz = txtEintragZusatz.Text
        }

        RaiseEvent PersonenUebergabeEreignis(Me, args)
    End Sub

    Private Sub dgHeiratDetails_AutoGeneratedColumns(sender As Object, e As EventArgs) Handles dgHeiratDetails.AutoGeneratedColumns
        For Each col In dgHeiratDetails.Columns
            If col.Header IsNot Nothing Then
                Select Case col.Header.ToString()
                    Case "tblFamilieID", "tblPersonIDV", "tblPersonIDM"
                        col.Visibility = Visibility.Collapsed
                End Select
            End If
        Next

        dgHeiratDetails.IsReadOnly = True
        dgHeiratDetails.CanUserAddRows = False
        dgHeiratDetails.CanUserDeleteRows = False
    End Sub

    Private Sub dgHeiratDetails_MouseDoubleClick(sender As Object, e As MouseButtonEventArgs)
        Dim rowView As DataRowView = CType(dgHeiratDetails.SelectedItem, DataRowView)
        If rowView IsNot Nothing Then
            Dim id As Integer = Convert.ToInt32(rowView("tblFamilieID"))
            CurrentFIDs(FType) = id
        End If
        ResetAllButtonsBackground(Me)
    End Sub

    Private Sub HFilterSetzen(search As String)
        Dim filter As String = vbNullString
        Dim sep As String = vbNullString

        If search.Trim() <> vbNullString Then
            filter = String.Format("FS LIKE '{0}%'", search.Trim().Substring(0, 4))
            sep = " AND "
        End If

        If Not String.IsNullOrEmpty(filter) Then
            Dim dv As New DataView(dtH)
            dv.RowFilter = filter
            dgHeiratDetails.ItemsSource = dv
        Else
            dgHeiratDetails.ItemsSource = dtH.DefaultView
        End If


        For Each rowView As DataRowView In dgHeiratDetails.Items
            If rowView("FS") = lblVTag.Text.Trim() Then
                dgHeiratDetails.SelectedItem = rowView
                dgHeiratDetails.ScrollIntoView(rowView)

                Exit For
            End If
        Next
    End Sub

    Private Sub txtIndexH_GotFocus(sender As Object, e As RoutedEventArgs) Handles txtIndexH.GotFocus, txtIndexBt.GotFocus, txtIndexBtg.GotFocus
        HFilterSetzen(sender.text)
        Select Case sender.name
            Case "txtIndexH"
                FType = PersonTyp.Btg
            Case "txtIndexBt"
                FType = PersonTyp.MBtg
            Case "txtIndexBtg"
                FType = PersonTyp.VBtg
        End Select
    End Sub

    Private Sub btnNewHEintrag_Click(sender As Object, e As RoutedEventArgs) Handles btnNewHEintrag.Click
        If FType <> PersonTyp.Btg Then
            txtEhemann.Text = ""
            txtEhefrau.Text = ""
            Using conn As New OleDbConnection(connectionString)
                conn.Open()
                ResetAllButtonsBackground(Me)
                DaT = "0000"
                Dim sql As String = pSQL & " WHERE tblVKHID = ?"
                Using cmd As New OleDbCommand(sql, conn)
                    cmd.Parameters.AddWithValue("@p1", ID)

                    Using reader As OleDbDataReader = cmd.ExecuteReader()
                        If reader.Read() Then
                            If Not IsDBNull(reader("VN_BR")) Then
                                txtEhemann.Text = reader("VN_BR") & " "
                            End If
                            If Not IsDBNull(reader("FN_BR")) Then
                                txtEhemann.Text &= reader("FN_BR").ToString.ToUpper
                            End If
                            If Not IsDBNull(reader("VN_BT")) Then
                                txtEhefrau.Text = reader("VN_BT") & " "
                            End If
                            If Not IsDBNull(reader("FN_BT")) Then
                                txtEhefrau.Text &= reader("FN_BT").ToString.ToUpper
                            End If


                            HFilterSetzen(txtIndexH.Text)
                        Else
                            MessageBox.Show("Kein Eintrag mit dieser ID gefunden.")
                        End If
                    End Using
                End Using
            End Using
            FType = PersonTyp.Btg
            Exit Sub
        End If
        FType = PersonTyp.Btg
        Dim VID As Integer = 0
        If CurrentIDs.TryGetValue(PersonTyp.Btg, VID) Then
            'MessageBox.Show($"ID gefunden: {pid} Typ {btn.Name} ")
        End If

        Dim MID As Integer = 0
        If CurrentIDs.TryGetValue(PersonTyp.Bt, MID) Then
            'MessageBox.Show($"ID gefunden: {pid} Typ {btn.Name} ")
        End If

        Dim FID As Integer = 0
        'If CurrentIDs.TryGetValue(PersonTyp.Btg, VID) Then
        '    'MessageBox.Show($"ID gefunden: {pid} Typ {btn.Name} ")
        'End If

        Dim CID As Integer = 0

        Dim args As New FamilyUebergabeEventArgs With {
            .FID = 0,
            .VID = VID,
            .MID = MID,
            .CID = 0,
            .EventDatum = txtHDatum.Text,
            .EventArt = "Heirat",
            .Referenz = "H " & txtNr.Text,
            .OnlineRef = txtURL.Text,
            .Ort = txtWO.Text,
            .Zusatz = txtInfo.Text
        }
        RaiseEvent FamilyUbergabe(Me, args)
        HFilterSetzen(txtIndexH.Text)
        btnNewHEintrag.Background = Brushes.LightGreen
    End Sub

    Private Sub btnNewHVEintrag_Click(sender As Object, e As RoutedEventArgs) Handles btnNewHVEintrag.Click
        If FType <> PersonTyp.VBtg Then
            txtEhemann.Text = ""
            txtEhefrau.Text = ""
            Using conn As New OleDbConnection(connectionString)
                conn.Open()
                ResetAllButtonsBackground(Me)
                DaT = "0000"
                Dim sql As String = pSQL & " WHERE tblVKHID = ?"
                Using cmd As New OleDbCommand(sql, conn)
                    cmd.Parameters.AddWithValue("@p1", ID)

                    Using reader As OleDbDataReader = cmd.ExecuteReader()
                        If reader.Read() Then
                            If Not IsDBNull(reader("VN_VBR")) Then
                                txtEhemann.Text = reader("VN_VBR") & " "
                            End If
                            If Not IsDBNull(reader("FN_VBR")) Then
                                txtEhemann.Text &= reader("FN_VBR").ToString.ToUpper
                            End If
                            If Not IsDBNull(reader("VN_MBR")) Then
                                txtEhefrau.Text = reader("VN_MBR") & " "
                            End If
                            If Not IsDBNull(reader("FN_VBR")) Then
                                txtEhefrau.Text &= reader("FN_MBR").ToString.ToUpper
                            End If


                            HFilterSetzen(txtIndexBtg.Text)
                        Else
                            MessageBox.Show("Kein Eintrag mit dieser ID gefunden.")
                        End If
                    End Using
                End Using
            End Using
            FType = PersonTyp.VBtg
            Exit Sub
        End If
        FType = PersonTyp.VBtg
        Dim VID As Integer = 0
        If CurrentIDs.TryGetValue(PersonTyp.VBtg, VID) Then
            'MessageBox.Show($"ID gefunden: {pid} Typ {btn.Name} ")
        End If

        Dim MID As Integer = 0
        If CurrentIDs.TryGetValue(PersonTyp.MBtg, MID) Then
            'MessageBox.Show($"ID gefunden: {pid} Typ {btn.Name} ")
        End If

        Dim FID As Integer = 0
        If CurrentFIDs.TryGetValue(PersonTyp.VBtg, FID) Then
            'MessageBox.Show($"ID gefunden: {pid} Typ {btn.Name} ")
        End If

        Dim CID As Integer = 0
        If CurrentIDs.TryGetValue(PersonTyp.Btg, CID) Then
            'MessageBox.Show($"ID gefunden: {pid} Typ {btn.Name} ")
        End If
        Dim args As New FamilyUebergabeEventArgs With {
            .FID = FID,
            .VID = VID,
            .MID = MID,
            .CID = CID,
            .EventDatum = "",
            .EventArt = "Heirat",
            .Referenz = "H " & txtNr.Text,
            .OnlineRef = txtURL.Text,
            .Ort = txtWO.Text,
            .Zusatz = txtInfo.Text
        }
        RaiseEvent FamilyUbergabe(Me, args)
        HFilterSetzen(txtIndexBtg.Text)
        btnNewHVEintrag.Background = Brushes.LightGreen
    End Sub

    Private Sub btnNewHMEintrag_Click(sender As Object, e As RoutedEventArgs) Handles btnNewHMEintrag.Click
        If FType <> PersonTyp.VBt Then
            txtEhemann.Text = ""
            txtEhefrau.Text = ""
            Using conn As New OleDbConnection(connectionString)
                conn.Open()
                ResetAllButtonsBackground(Me)
                DaT = "0000"
                Dim sql As String = pSQL & " WHERE tblVKHID = ?"
                Using cmd As New OleDbCommand(sql, conn)
                    cmd.Parameters.AddWithValue("@p1", ID)

                    Using reader As OleDbDataReader = cmd.ExecuteReader()
                        If reader.Read() Then
                            If Not IsDBNull(reader("VN_VBT")) Then
                                txtEhemann.Text = reader("VN_VBT") & " "
                            End If
                            If Not IsDBNull(reader("FN_VBT")) Then
                                txtEhemann.Text &= reader("FN_VBT").ToString.ToUpper
                            End If
                            If Not IsDBNull(reader("VN_MBT")) Then
                                txtEhefrau.Text = reader("VN_MBT") & " "
                            End If
                            If Not IsDBNull(reader("FN_MBT")) Then
                                txtEhefrau.Text &= reader("FN_MBT").ToString.ToUpper
                            End If


                            HFilterSetzen(txtIndexBt.Text)
                        Else
                            MessageBox.Show("Kein Eintrag mit dieser ID gefunden.")
                        End If
                    End Using
                End Using
            End Using
            FType = PersonTyp.VBt
            Exit Sub
        End If
        FType = PersonTyp.VBt
        Dim VID As Integer = 0
        If CurrentIDs.TryGetValue(PersonTyp.VBt, VID) Then
            'MessageBox.Show($"ID gefunden: {pid} Typ {btn.Name} ")
        End If

        Dim MID As Integer = 0
        If CurrentIDs.TryGetValue(PersonTyp.MBt, MID) Then
            'MessageBox.Show($"ID gefunden: {pid} Typ {btn.Name} ")
        End If

        Dim FID As Integer = 0
        If CurrentFIDs.TryGetValue(PersonTyp.VBt, FID) Then
            'MessageBox.Show($"ID gefunden: {pid} Typ {btn.Name} ")
        End If

        Dim CID As Integer = 0
        If CurrentIDs.TryGetValue(PersonTyp.Bt, CID) Then
            'MessageBox.Show($"ID gefunden: {pid} Typ {btn.Name} ")
        End If
        Dim args As New FamilyUebergabeEventArgs With {
            .FID = FID,
            .VID = VID,
            .MID = MID,
            .CID = CID,
            .EventDatum = "",
            .EventArt = "Heirat",
            .Referenz = "H " & txtNr.Text,
            .OnlineRef = txtURL.Text,
            .Ort = txtWO.Text,
            .Zusatz = txtInfo.Text
        }
        RaiseEvent FamilyUbergabe(Me, args)
        HFilterSetzen(txtIndexBt.Text)
        btnNewHMEintrag.Background = Brushes.LightGreen
    End Sub
End Class
