Imports System.Data
Imports inoGenDLL

Public Class vornamen
    Private cGDB As New ClsGenDB(My.Settings.DBPath)

    Private dtVorname As DataTable
    Private dvVorname As DataView

    Private Sub TxtSuche_TextChanged(sender As Object, e As TextChangedEventArgs) Handles TxtSuche.TextChanged
        If dvVorname Is Nothing Then Exit Sub

        Dim filter = TxtSuche.Text.Replace("'", "''") ' Schutz
        dvVorname.RowFilter = $"Vorname LIKE '%{filter}%'"
    End Sub

    Private Sub vornamen_Initialized(sender As Object, e As EventArgs) Handles Me.Initialized
        UpdateData()
        TxtID.IsEnabled = False
    End Sub

    Private Sub DgVorname_MouseDoubleClick(sender As Object, e As MouseButtonEventArgs) Handles DgVorname.MouseDoubleClick
        Dim rowView = TryCast(DgVorname.SelectedItem, DataRowView)
        If rowView Is Nothing Then Exit Sub

        TxtID.Text = rowView("tblVornameID").ToString()
        TxtVorname.Text = rowView("Vorname").ToString()
        TxtStammname.Text = rowView("CPStVorname").ToString()

    End Sub

    Private Sub BtnSelect_Click(sender As Object, e As RoutedEventArgs)

        Dim rowView = TryCast(DgVorname.SelectedItem, DataRowView)
        If rowView Is Nothing Then
            MessageBox.Show("Bitte Datensatz auswählen")
            Return
        End If

        Dim id As Integer = CInt(rowView("ID"))
        Dim nachname As String = rowView("Vorname").ToString()

    End Sub

    Private Sub UpdateData()
        dtVorname = cGDB.GetVornamen
        dvVorname = dtVorname.DefaultView
        DgVorname.ItemsSource = dvVorname
    End Sub

    Private Sub BtnSave_Click(sender As Object, e As RoutedEventArgs)

        cGDB.UpdateVorname(TxtID.Text, TxtVorname.Text, TxtStammname.Text.Trim)
        UpdateData()

    End Sub

    Private Sub DgVorname_AutoGeneratedColumns(sender As Object, e As EventArgs) Handles DgVorname.AutoGeneratedColumns
        For Each col In DgVorname.Columns
            If col.Header IsNot Nothing Then
                Select Case col.Header.ToString()
                    Case "tblVornameID", "SVorname", "CPVorname", "CPSVorname"
                        col.Visibility = Visibility.Collapsed
                End Select
            End If
        Next

        DgVorname.IsReadOnly = True
        DgVorname.CanUserAddRows = False
        DgVorname.CanUserDeleteRows = False
    End Sub
End Class
