'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Automatische My.Settings-Speicherfunktion"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DBPath() As String
            Get
                Return CType(Me("DBPath"),String)
            End Get
            Set
                Me("DBPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property LastPID() As Integer
            Get
                Return CType(Me("LastPID"),Integer)
            End Get
            Set
                Me("LastPID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property LastFID() As Integer
            Get
                Return CType(Me("LastFID"),Integer)
            End Get
            Set
                Me("LastFID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property RecentFiles() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("RecentFiles"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("RecentFiles") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property LastVKHID() As Integer
            Get
                Return CType(Me("LastVKHID"),Integer)
            End Get
            Set
                Me("LastVKHID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastContent() As String
            Get
                Return CType(Me("LastContent"),String)
            End Get
            Set
                Me("LastContent") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Email() As String
            Get
                Return CType(Me("Email"),String)
            End Get
            Set
                Me("Email") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property LastKJ() As Integer
            Get
                Return CType(Me("LastKJ"),Integer)
            End Get
            Set
                Me("LastKJ") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastPlace() As String
            Get
                Return CType(Me("LastPlace"),String)
            End Get
            Set
                Me("LastPlace") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property LastVKHIDÜbergabe() As Integer
            Get
                Return CType(Me("LastVKHIDÜbergabe"),Integer)
            End Get
            Set
                Me("LastVKHIDÜbergabe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CurrentWork() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("CurrentWork"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("CurrentWork") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property AutoCorrection() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("AutoCorrection"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("AutoCorrection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Gen4")>  _
        Public Property LastGenPrintout() As String
            Get
                Return CType(Me("LastGenPrintout"),String)
            End Get
            Set
                Me("LastGenPrintout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DIN1")>  _
        Public Property LastGenPapersize() As String
            Get
                Return CType(Me("LastGenPapersize"),String)
            End Get
            Set
                Me("LastGenPapersize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ohne")>  _
        Public Property LastGenColortype() As String
            Get
                Return CType(Me("LastGenColortype"),String)
            End Get
            Set
                Me("LastGenColortype") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Gen71() As Global.System.Drawing.Color
            Get
                Return CType(Me("Gen71"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Gen71") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Gen72() As Global.System.Drawing.Color
            Get
                Return CType(Me("Gen72"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Gen72") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Gen73() As Global.System.Drawing.Color
            Get
                Return CType(Me("Gen73"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Gen73") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Gen74S() As Global.System.Drawing.Color
            Get
                Return CType(Me("Gen74S"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Gen74S") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Gen74E() As Global.System.Drawing.Color
            Get
                Return CType(Me("Gen74E"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Gen74E") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Gen75S() As Global.System.Drawing.Color
            Get
                Return CType(Me("Gen75S"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Gen75S") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Gen75E() As Global.System.Drawing.Color
            Get
                Return CType(Me("Gen75E"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Gen75E") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Gen76S() As Global.System.Drawing.Color
            Get
                Return CType(Me("Gen76S"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Gen76S") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Gen76E() As Global.System.Drawing.Color
            Get
                Return CType(Me("Gen76E"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Gen76E") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Gen77S() As Global.System.Drawing.Color
            Get
                Return CType(Me("Gen77S"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Gen77S") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Gen77E() As Global.System.Drawing.Color
            Get
                Return CType(Me("Gen77E"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Gen77E") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property QZQuelle() As Long
            Get
                Return CType(Me("QZQuelle"),Long)
            End Get
            Set
                Me("QZQuelle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property QZEreignis() As Long
            Get
                Return CType(Me("QZEreignis"),Long)
            End Get
            Set
                Me("QZEreignis") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property QZJahr() As String
            Get
                Return CType(Me("QZJahr"),String)
            End Get
            Set
                Me("QZJahr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property QZBd() As String
            Get
                Return CType(Me("QZBd"),String)
            End Get
            Set
                Me("QZBd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property QZNummer() As String
            Get
                Return CType(Me("QZNummer"),String)
            End Get
            Set
                Me("QZNummer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property QZSeite() As String
            Get
                Return CType(Me("QZSeite"),String)
            End Get
            Set
                Me("QZSeite") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.inoGen.My.MySettings
            Get
                Return Global.inoGen.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
