ALTER TABLE tblVorname ADD COLUMN SVorname VARCHAR(4);
ALTER TABLE tblVorname ADD COLUMN CPVorname VARCHAR(50);
ALTER TABLE tblVorname ADD COLUMN CPStVorname VARCHAR(255);
ALTER TABLE tblVorname ADD COLUMN CPSVorname VARCHAR(50);


ALTER TABLE tblNachname ADD COLUMN SNachname VARCHAR(4);
ALTER TABLE tblNachname ADD COLUMN CPNachname VARCHAR(50);
ALTER TABLE tblNachname ADD COLUMN CPStNachname VARCHAR(255);
ALTER TABLE tblNachname ADD COLUMN CPSNachname VARCHAR(50);

UPDATE tblVersion SET Version = 12;
