ALTER TABLE tblVKH ADD COLUMN Info MEMO;

UPDATE tblVKH SET Info = ANM_H;

ALTER TABLE tblVKH DROP COLUMN ANM_H;

ALTER TABLE tblVKH ADD COLUMN ANM_H MEMO;

UPDATE tblVKH SET ANM_H = Info;

ALTER TABLE tblVKH DROP COLUMN Info;

UPDATE tblVersion SET Version = 8;